---
title: "Pandas Fundamentals"
format: 
  html:
    code-fold: false
    toc-depth: 4
jupyter: python3
---

## Introduction

Pandas is an essential tool in the data scientist or data analyst’s toolkit due to its ability to handle and transform data with ease and efficiency.

<img src="https://i.imgur.com/zfxLzEv.png" alt="example image" style="width: 750px;"/>

Built on top of the NumPy package, Pandas extends the capabilities of NumPy by offering support for working with tabular or heterogeneous data. While NumPy is optimized for working with homogeneous numerical arrays, Pandas is specifically designed for handling structured, labeled data, commonly represented in two-dimensional tables known as DataFrames.
There are some similarities between the two libraries. Like NumPy, Pandas provides basic mathematical functionalities such as addition, subtraction, conditional operations, and broadcasting. However, while NumPy focuses on multi-dimensional arrays, Pandas excels in offering the powerful 2D `DataFrame` object for data manipulation.

Data in Pandas is often used to feed statistical analyses in SciPy, visualization functions in Matplotlib, and machine learning algorithms in Scikit-learn.

Typically, the Pandas library is used for:

- Data reading/writing from different sources (CSV, Excel, SQL, etc.).
- Data manipulation, cleaning, and transformation.
- Computing data distribution and summary statistics
- Grouping, aggregation, and pivoting for advanced data analysis.
- Merging, concatenating, and reshaping data.
- Handling time series and datetime data.
- Data visualization and plotting.

Let's import the Pandas library to use its methods and functions.

In [2]:
import pandas as pd

## Creating a Pandas Series / DataFrame

* From a Python List or Dictionary
* By Reading Data from a file

### Creating a Series/DataFrame from Python List or Dictionary

#### Creating a series:

* **From a Python List**: You can create a pandas Series by passing a list of values.

In [8]:
#Defining a Pandas Series
series_example = pd.Series(['these','are','english','words'])
series_example

0      these
1        are
2    english
3      words
dtype: object

Note that the default row indices are integers starting from 0. However, the index can be specified with the `index` argument if desired by the user:

In [9]:
#Defining a Pandas Series with custom row labels
series_example = pd.Series(['these','are','english','words'], index = range(101,105))
series_example

101      these
102        are
103    english
104      words
dtype: object

* **From a Dictionary**: A dictionary can also be used to create a Series, where keys become index labels.

In [10]:
#Dictionary consisting of the GDP per capita of the US from 1960 to 2021 with some missing values
GDP_per_capita_dict = {'1960':3007,'1961':3067,'1962':3244,'1963':3375,'1964':3574,'1965':3828,'1966':4146,'1967':4336,'1968':4696,'1970':5234,'1971':5609,'1972':6094,'1973':6726,'1974':7226,'1975':7801,'1976':8592,'1978':10565,'1979':11674, '1980':12575,'1981':13976,'1982':14434,'1983':15544,'1984':17121,'1985':18237,  '1986':19071,'1987':20039,'1988':21417,'1989':22857,'1990':23889,'1991':24342,  '1992':25419,'1993':26387,'1994':27695,'1995':28691,'1996':29968,'1997':31459,  '1998':32854,'2000':36330,'2001':37134,'2002':37998,'2003':39490,'2004':41725,  '2005':44123,'2006':46302,'2007':48050,'2008':48570,'2009':47195,'2010':48651,  '2011':50066,'2012':51784,'2013':53291,'2015':56763,'2016':57867,'2017':59915,'2018':62805, '2019':65095,'2020':63028,'2021':69288}

In [11]:
#Example 2: Creating a Pandas Series from a Dictionary
GDP_per_capita_series = pd.Series(GDP_per_capita_dict)
GDP_per_capita_series.head()

1960    3007
1961    3067
1962    3244
1963    3375
1964    3574
dtype: int64

#### Creating a DataFrame

* **From a list of Python Dictionary**: You can create a DataFrame where keys are column names and values are lists representing column data.

In [12]:
#List of dictionary consisting of 52 playing cards of the deck
deck_list_of_dictionaries = [{'value':i, 'suit':c}
for c in ['spades', 'clubs', 'hearts', 'diamonds']
for i in range(2,15)]

In [13]:
#Example 3: Creating a Pandas DataFrame from a List of dictionaries
deck_df = pd.DataFrame(deck_list_of_dictionaries)
deck_df.head()

   value    suit
0      2  spades
1      3  spades
2      4  spades
3      5  spades
4      6  spades

* **From a Python Dictionary**: You can create a DataFrame where keys are column names and values are lists representing column data.

In [14]:
#Example 4: Creating a Pandas DataFrame from a Dictionary
dict_data = {'A': [1, 2, 3, 4, 5],
        'B': [20, 10, 50, 40, 30],
        'C': [100, 200, 300, 400, 500]}

dict_df = pd.DataFrame(dict_data)
dict_df

   A   B    C
0  1  20  100
1  2  10  200
2  3  50  300
3  4  40  400
4  5  30  500

## Creating a Series/DataFrame by Reading Data from a File

In the real world, a Pandas DataFrame will typically be created by loading the datasets from existing storage such as SQL Database, CSV file, Excel file, text files, HTML files, etc., as we learned in the perious chapter of the book on Reading data.

* **Using `read_csv()`**: This is one of the most common methods to read data from a CSV file into a pandas DataFrame.
* **Using `read_excel()`**: You can also read data from Excel files.
* **Using `read_json()`**: You can also read data from json files.

## Pandas data structures - Series and DataFrame

There are two core components of the Pandas library - Series and DataFrame.

A DataFrame is a two-dimensional object - comprising of tabular data organized in rows and columns, where individual columns can be of different value types (numeric / string / boolean etc.). A DataFrame has row labels (also called row indices) which refer to individual rows, and column labels (also called column names) that refer to individual columns. By default, the row indices are integers starting from zero. However, both the row indices and column names can be customized by the user.

Let us read the spotify data - *spotify_data.csv*, using the Pandas function `read_csv()`.

In [ ]:
movie_ratings = pd.read_csv('./datasets/movie_ratings.csv')
movie_ratings.head()

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
0,Opal Dreams,14443,14443,9000000,Nov 22 2006,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,468
1,Major Dundee,14873,14873,3800000,Apr 07 1965,PG/PG-13,Adapted screenplay,Western/Musical,Fiction,6.7,2588
2,The Informers,315000,315000,18000000,Apr 24 2009,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,7595
3,Buffalo Soldiers,353743,353743,15000000,Jul 25 2003,R,Adapted screenplay,Comedy,Fiction,6.9,13510
4,The Last Sin Eater,388390,388390,2200000,Feb 09 2007,PG/PG-13,Adapted screenplay,Drama,Fiction,5.7,1012

The object `spotify_data` is a pandas DataFrame:

In [ ]:
type(movie_ratings)

pandas.core.frame.DataFrame

 A Series is a one-dimensional array-like object in pandas that contains a sequence of values, where each value is associated with an index. All the values in a Series must have the same data type.  Each column of a DataFrame is Series as shown in the example below.

In [ ]:
#Extracting song titles from the spotify_songs DataFrame
movie_title = movie_ratings['Title']
movie_title

0                         Opal Dreams
1                        Major Dundee
2                       The Informers
3                    Buffalo Soldiers
4                  The Last Sin Eater
                    ...
2223                      King Arthur
2224                            Mulan
2225                       Robin Hood
2226    Robin Hood: Prince of Thieves
2227                       Spiceworld
Name: Title, Length: 2228, dtype: object

In [ ]:
#The object spotify_songs is a Series
type(movie_title)

pandas.core.series.Series

A Series is essentially a column, and a DataFrame is a two-dimensional table made up of a collection of Series



<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFmjpTWPpi4cZBAuL7W5H1LvGetG_MwnmvGQ&s" alt="example image" style="width: 300px;"/>

## Data Selection and Filtering

###  Extracting Column(s)

The first step when working with a DataFrame is often to extract one or more columns. To do this effectively, it’s helpful to understand the internal structure of a DataFrame. Conceptually, you can think of a DataFrame as a dictionary of lists, where the keys are column names, and the values are lists or arrays containing data for the respective columns.

In [ ]:
# Pandas format is simliar to this
movie_ratings_dict = {
    'Title':  ['Opal Dreams', 'Major Dundee', 'The Informers', 'Buffalo Soldiers', 'The Last Sin Eater'],
    'US Gross':  [14443, 14873, 315000, 353743, 388390],
    'Worldwide Gross': [14443, 14873, 315000, 353743, 388390],
    'Production Budget': [9000000, 3800000, 18000000, 15000000, 2200000]
}

 For dictionary, we use key to retrive its values

In [ ]:
movie_ratings_dict['Title']

['Opal Dreams',
 'Major Dundee',
 'The Informers',
 'Buffalo Soldiers',
 'The Last Sin Eater']

Similar like dictionary, we can extract a column by its column name

In [ ]:
movie_ratings['Title']

0                         Opal Dreams
1                        Major Dundee
2                       The Informers
3                    Buffalo Soldiers
4                  The Last Sin Eater
                    ...
2223                      King Arthur
2224                            Mulan
2225                       Robin Hood
2226    Robin Hood: Prince of Thieves
2227                       Spiceworld
Name: Title, Length: 2228, dtype: object


Each column is a feature of the dataframe, we can also use`.` operator to extract a single column

In [ ]:
movie_ratings.Title

0                         Opal Dreams
1                        Major Dundee
2                       The Informers
3                    Buffalo Soldiers
4                  The Last Sin Eater
                    ...
2223                      King Arthur
2224                            Mulan
2225                       Robin Hood
2226    Robin Hood: Prince of Thieves
2227                       Spiceworld
Name: Title, Length: 2228, dtype: object

When extracting multiple columns, you need to place the column names inside a list.

In [ ]:
movie_ratings[['Title', 'US Gross', 'Worldwide Gross' ]]

                              Title   US Gross  Worldwide Gross
0                       Opal Dreams      14443            14443
1                      Major Dundee      14873            14873
2                     The Informers     315000           315000
3                  Buffalo Soldiers     353743           353743
4                The Last Sin Eater     388390           388390
...                             ...        ...              ...
2223                    King Arthur   51877963        203877963
2224                          Mulan  120620254        303500000
2225                     Robin Hood  105269730        310885538
2226  Robin Hood: Prince of Thieves  165493908        390500000
2227                     Spiceworld   29342592         56042592

[2228 rows x 3 columns]

### Extracting Row(s) 

#### Extracting based on a Single Condition or Multiple Conditions

In many cases, we need to filter rows based on specific conditions or a combination of multiple conditions. Next, let’s explore how to use these conditions effectively to extract rows that meet our criteria, whether it's a single condition or multiple conditions combined

In [ ]:
# extracting the rows that have IMDB Rating greater than 8
movie_ratings[movie_ratings['IMDB Rating'] > 8]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
21,"Gandhi, My Father",240425,1375194,5000000,Aug 03 2007,Other,Adapted screenplay,Drama,Non-Fiction,8.1,50881
56,Ed Wood,5828466,5828466,18000000,Sep 30 1994,R,Adapted screenplay,Comedy,Non-Fiction,8.1,74171
67,Requiem for a Dream,3635482,7390108,4500000,Oct 06 2000,Other,Adapted screenplay,Drama,Fiction,8.5,185226
164,Trainspotting,16501785,24000785,3100000,Jul 19 1996,R,Adapted screenplay,Drama,Fiction,8.2,150483
181,The Wizard of Oz,28202232,28202232,2777000,Aug 25 2039,G,Adapted screenplay,Western/Musical,Fiction,8.3,102795
...,...,...,...,...,...,...,...,...,...,...,...
2090,Finding Nemo,339714978,867894287,94000000,May 30 2003,G,Original Screenplay,Action/Adventure,Fiction,8.2,165006
2092,Toy Story 3,410640665,1046340665,200000000,Jun 18 2010,G,Original Screenplay,Action/Adventure,Fiction,8.9,67380
2094,Avatar,760167650,2767891499,237000000,Dec 18 2009,PG/PG-13,Original Screenplay,Action/Adventure,Fiction,8.3,261439
2130,Scarface,44942821,44942821,25000000,Dec 09 1983,Other,Adapted screenplay,Drama,Fiction,8.2,152262
2194,The Departed,133311000,290539042,90000000,Oct 06 2006,R,Adapted screenplay,Drama,Fiction,8.5,264148

To combine multiple conditions in pandas, you need to use the `&` (AND) and `|` (OR) operators. Make sure to enclose each condition in parentheses () for clarity and to ensure proper evaluation order.

In [ ]:
# extracting the rows that have IMDB Rating greater than 8 and US Gross less than 1000000
movie_ratings[(movie_ratings['IMDB Rating'] > 8) & (movie_ratings['US Gross'] < 1000000)]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
21,"Gandhi, My Father",240425,1375194,5000000,Aug 03 2007,Other,Adapted screenplay,Drama,Non-Fiction,8.1,50881
636,Lake of Fire,25317,25317,6000000,Oct 03 2007,Other,Adapted screenplay,Documentary,Non-Fiction,8.4,1027

#### Negating Conditions with the `~` Operator

The tilde (`~`) is used for negating boolean conditions in pandas, making it a useful tool for excluding specific values or rows.

In some cases, we may want to extract rows that do not meet a specific condition. To accomplish this, we can use the `~` operator, which negates a condition. This operator allows us to filter data by excluding rows that satisfy a particular condition, making it a powerful tool for refining our queries. Let’s explore how to use the `~` operator to negate conditions and select rows that do not meet our criteria

In [ ]:
# Excluding the rows that have IMDB Rating that equals 8 using the tilde ~
movie_ratings[~(movie_ratings['IMDB Rating'] == 8)]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
0,Opal Dreams,14443,14443,9000000,Nov 22 2006,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,468
1,Major Dundee,14873,14873,3800000,Apr 07 1965,PG/PG-13,Adapted screenplay,Western/Musical,Fiction,6.7,2588
2,The Informers,315000,315000,18000000,Apr 24 2009,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,7595
3,Buffalo Soldiers,353743,353743,15000000,Jul 25 2003,R,Adapted screenplay,Comedy,Fiction,6.9,13510
4,The Last Sin Eater,388390,388390,2200000,Feb 09 2007,PG/PG-13,Adapted screenplay,Drama,Fiction,5.7,1012
...,...,...,...,...,...,...,...,...,...,...,...
2223,King Arthur,51877963,203877963,90000000,Jul 07 2004,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.2,53106
2224,Mulan,120620254,303500000,90000000,Jun 19 1998,G,Adapted screenplay,Action/Adventure,Non-Fiction,7.2,34256
2225,Robin Hood,105269730,310885538,210000000,May 14 2010,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.9,34501
2226,Robin Hood: Prince of Thieves,165493908,390500000,50000000,Jun 14 1991,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.7,54480
2227,Spiceworld,29342592,56042592,25000000,Jan 23 1998,PG/PG-13,Adapted screenplay,Comedy,Fiction,2.9,18010

Another way to exclude rows where a column equals a certain value, you can use `!=` to create the condition.

In [ ]:
# using the != operator
movie_ratings[movie_ratings['IMDB Rating'] != 8]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
0,Opal Dreams,14443,14443,9000000,Nov 22 2006,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,468
1,Major Dundee,14873,14873,3800000,Apr 07 1965,PG/PG-13,Adapted screenplay,Western/Musical,Fiction,6.7,2588
2,The Informers,315000,315000,18000000,Apr 24 2009,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,7595
3,Buffalo Soldiers,353743,353743,15000000,Jul 25 2003,R,Adapted screenplay,Comedy,Fiction,6.9,13510
4,The Last Sin Eater,388390,388390,2200000,Feb 09 2007,PG/PG-13,Adapted screenplay,Drama,Fiction,5.7,1012
...,...,...,...,...,...,...,...,...,...,...,...
2223,King Arthur,51877963,203877963,90000000,Jul 07 2004,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.2,53106
2224,Mulan,120620254,303500000,90000000,Jun 19 1998,G,Adapted screenplay,Action/Adventure,Non-Fiction,7.2,34256
2225,Robin Hood,105269730,310885538,210000000,May 14 2010,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.9,34501
2226,Robin Hood: Prince of Thieves,165493908,390500000,50000000,Jun 14 1991,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.7,54480
2227,Spiceworld,29342592,56042592,25000000,Jan 23 1998,PG/PG-13,Adapted screenplay,Comedy,Fiction,2.9,18010

### Extracting Subsets of Rows and Columns

Sometimes we may be interested in working with a subset of rows and columns of the data, instead of working with the entire dataset. The indexing operators [loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) and [iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html) provide a convenient way of selecting a subset of desired rows and columns. 

Let us first sort the `movie_ratings` data frame by `IMDB Rating`.

In [ ]:
movie_ratings_sorted = movie_ratings.sort_values(by = 'IMDB Rating', ascending = False)
movie_ratings_sorted.head()

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
182,The Shawshank Redemption,28241469,28241469,25000000,Sep 23 1994,R,Adapted screenplay,Drama,Fiction,9.2,519541
2084,Inception,285630280,753830280,160000000,Jul 16 2010,PG/PG-13,Original Screenplay,Horror/Thriller,Fiction,9.1,188247
790,Schindler's List,96067179,321200000,25000000,Dec 15 1993,R,Adapted screenplay,Drama,Non-Fiction,8.9,276283
1962,Pulp Fiction,107928762,212928762,8000000,Oct 14 1994,R,Original Screenplay,Drama,Fiction,8.9,417703
561,The Dark Knight,533345358,1022345358,185000000,Jul 18 2008,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,8.9,465000

#### Subsetting the DataFrame by `loc`
The operator `loc` uses axis labels (row indices and column names) to subset the data.


Let's subset the `title`, `worldwide gross`, `production budget`, and `IMDB raring` of top 3 movies.

In [ ]:
# Subsetting the DataFrame by loc - using axis labels
movies_subset = movie_ratings_sorted.loc[[182,2084, 2092],[ 'Title', 'IMDB Rating', 'US Gross', 'Worldwide Gross', 'Production Budget']]
movies_subset

,Title,IMDB Rating,US Gross,Worldwide Gross,Production Budget
182,The Shawshank Redemption,9.2,28241469,28241469,25000000
2084,Inception,9.1,285630280,753830280,160000000
2092,Toy Story 3,8.9,410640665,1046340665,200000000

The `:` symbol in `.loc` is a slicing operator that represents a range or all elements in the specified dimension (rows or columns). Use `:` alone to select all rows/columns, or with start/end points to slice specific parts of the DataFrame.

In [ ]:
# Subsetting the DataFrame by loc - using axis labels. the colon is used to select all rows
movies_subset = movie_ratings_sorted.loc[:,['Title','Worldwide Gross','Production Budget','IMDB Rating']]
movies_subset

,Title,Worldwide Gross,Production Budget,IMDB Rating
182,The Shawshank Redemption,28241469,25000000,9.2
2084,Inception,753830280,160000000,9.1
790,Schindler's List,321200000,25000000,8.9
1962,Pulp Fiction,212928762,8000000,8.9
561,The Dark Knight,1022345358,185000000,8.9
...,...,...,...,...
1051,Glitter,4273372,8500000,2.0
1495,Disaster Movie,34690901,20000000,1.7
1116,Crossover,7009668,5600000,1.7
805,From Justin to Kelly,4922166,12000000,1.6
1147,Super Babies: Baby Geniuses 2,9109322,20000000,1.4

In [ ]:
# Subsetting the DataFrame by loc - using axis labels. the colon is used to select a range of rows
movies_subset = movie_ratings_sorted.loc[182:561,['Title','Worldwide Gross','Production Budget','IMDB Rating']]
movies_subset

,Title,Worldwide Gross,Production Budget,IMDB Rating
182,The Shawshank Redemption,28241469,25000000,9.2
2084,Inception,753830280,160000000,9.1
790,Schindler's List,321200000,25000000,8.9
1962,Pulp Fiction,212928762,8000000,8.9
561,The Dark Knight,1022345358,185000000,8.9

**Combining `.loc` with condition(s)** to extract specific rows and columns based on criteria

In [ ]:
# extracting the rows that have IMDB Rating greater than 8 or US Gross less than 1000000, only extract the Title and IMDB Rating columns
movie_ratings[(movie_ratings['IMDB Rating'] > 8) & (movie_ratings['US Gross'] < 1000000)][['Title','IMDB Rating']]

#using loc to extract the rows that have IMDB Rating greater than 8 or US Gross less than 1000000, only extract the Title and IMDB Rating columns
movie_ratings.loc[(movie_ratings['IMDB Rating'] > 8) & (movie_ratings['US Gross'] < 1000000),['Title','IMDB Rating']]

                 Title  IMDB Rating
21   Gandhi, My Father          8.1
636       Lake of Fire          8.4

#### Subsetting the DataFrame by `iloc`

while `iloc` uses the position of rows or columns, where position has values 0,1,2,3,…and so on, for rows from top to bottom and columns from left to right. In other words, the first row has position 0, the second row has position 1, the third row has position 2, and so on. Similarly, the first column from left has position 0, the second column from left has position 1, the third column from left has position 2, and so on.

In [ ]:
#| echo: false

# import image module
from IPython.display import Image

# get the image
Image(url="./images/pandas-iloc-loc-index-types.png",width=450)

In [ ]:
# let's check  the movie_ratings_sorted DataFrame
movie_ratings_sorted.head()

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
182,The Shawshank Redemption,28241469,28241469,25000000,Sep 23 1994,R,Adapted screenplay,Drama,Fiction,9.2,519541
2084,Inception,285630280,753830280,160000000,Jul 16 2010,PG/PG-13,Original Screenplay,Horror/Thriller,Fiction,9.1,188247
790,Schindler's List,96067179,321200000,25000000,Dec 15 1993,R,Adapted screenplay,Drama,Non-Fiction,8.9,276283
1962,Pulp Fiction,107928762,212928762,8000000,Oct 14 1994,R,Original Screenplay,Drama,Fiction,8.9,417703
561,The Dark Knight,533345358,1022345358,185000000,Jul 18 2008,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,8.9,465000

After sorting, the position-based index changes, while the label-based index remains unchanged. Let’s pass the position-based index to `iloc` to retrieve the top 2 rows from the `movie_ratings_sorted` DataFrame.

In [ ]:
movie_ratings_sorted.iloc[0:2,:]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
182,The Shawshank Redemption,28241469,28241469,25000000,Sep 23 1994,R,Adapted screenplay,Drama,Fiction,9.2,519541
2084,Inception,285630280,753830280,160000000,Jul 16 2010,PG/PG-13,Original Screenplay,Horror/Thriller,Fiction,9.1,188247

It is important to note that the endpoint is excluded in an `iloc` slice.

For comparison, let’s pass the same argument to loc and see what it returns.

In [ ]:
movie_ratings_sorted.loc[0:2,:]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
0,Opal Dreams,14443,14443,9000000,Nov 22 2006,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,468
851,Star Trek: Generations,75671262,120000000,38000000,Nov 18 1994,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.5,26465
140,Tuck Everlasting,19161999,19344615,15000000,Oct 11 2002,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,6639
708,De-Lovely,13337299,18396382,4000000,Jun 25 2004,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,6086
705,Flyboys,13090630,14816379,60000000,Sep 22 2006,PG/PG-13,Adapted screenplay,Drama,Non-Fiction,6.5,13934
...,...,...,...,...,...,...,...,...,...,...,...
955,The Brothers Solomon,900926,900926,10000000,Sep 07 2007,R,Original Screenplay,Comedy,Fiction,5.2,6044
1637,Drumline,56398162,56398162,20000000,Dec 13 2002,PG/PG-13,Original Screenplay,Comedy,Fiction,5.2,18165
1610,Hollywood Homicide,30207785,51107785,75000000,Jun 13 2003,PG/PG-13,Original Screenplay,Action/Adventure,Fiction,5.2,16452
569,Doom,28212337,54612337,70000000,Oct 21 2005,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,39473
2,The Informers,315000,315000,18000000,Apr 24 2009,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,7595

As you can see, `:` is used in the same way as in `loc` to denote a range of the index. All rows between label indices 0 and 2, inclusive of both ends, are returned.

In [ ]:
# Subsetting the DataFrame by iloc - using index of the position of rows and columns
movies_iloc_subset1 = movie_ratings_sorted.iloc[0:10,[0,2,3,9]]
movies_iloc_subset1

,Title,Worldwide Gross,Production Budget,IMDB Rating
182,The Shawshank Redemption,28241469,25000000,9.2
2084,Inception,753830280,160000000,9.1
2092,Toy Story 3,1046340665,200000000,8.9
1962,Pulp Fiction,212928762,8000000,8.9
790,Schindler's List,321200000,25000000,8.9
561,The Dark Knight,1022345358,185000000,8.9
184,Cidade de Deus,28763397,3300000,8.8
487,The Lord of the Rings: The Fellowship of the Ring,868621686,109000000,8.8
497,The Lord of the Rings: The Return of the King,1133027325,94000000,8.8
1081,C'era una volta il West,5321508,5000000,8.8

Can you use `.iloc` for conditional filtering, why or why not?

 To recap, here are the **Key differences between`loc` and `iloc` in pandas**:

* **Indexing Type:**

    * loc uses labels (names) for indexing.
    * iloc uses integer positions for indexing.
* **Inclusion of Endpoints:**

    * In a loc slice, both endpoints are included.
    * In an iloc slice, the endpoint is excluded.

### Finding minimum/maximum of a column
When working with pandas, there are two main options for locating the minimum or maximum values in a DataFrame column: 

* `idxmin()` and `idxmax()`: return the **index label** of the first occurrence of the maximum or minimum value in a specified column.

In [ ]:
# movie_ratings_sorted.iloc[position_max_wgross,:]
max_index = movie_ratings_sorted['Worldwide Gross'].idxmax()
min_index = movie_ratings_sorted['Worldwide Gross'].idxmin()
print("Max index: ", max_index)
print("Min index: ", min_index)

Max index:  2094
Min index:  896

`idxmin()` and `idxmax()` return the index label of the minimum or maximum value in a column.
You can use these returned index labels with `.loc` to extract the corresponding row.

In [ ]:
print(movie_ratings_sorted.loc[max_index,'Worldwide Gross'])
print(movie_ratings_sorted.loc[min_index,'Worldwide Gross'])

2767891499
884

* `argmax()` and `argmin()`: Return the **integer position** of the first occurrence of the maximum or minimum value in a column. You can use these integer positions with `.iloc` to extract the corresponding row

In [ ]:
# using argmax and argmin, which return the index of the maximum and minimum values
max_position = movie_ratings_sorted['Worldwide Gross'].argmax()
min_position = movie_ratings_sorted['Worldwide Gross'].argmin()
print("max position:", max_position)
print("min position:", min_position)

# using iloc to get the row with the maximum and minimum values
print(movie_ratings_sorted.iloc[max_position, 2])
print(movie_ratings_sorted.iloc[min_position, 2])

max position: 48
min position: 2149
2767891499
884

**Tips:**

- When working with non-unique or custom indices, it is recommended to use `idxmax()` and `idxmin()` to retrieve index labels, as `argmax()` may be less intuitive in such scenarios.  
- For DataFrames, use `.idxmax(axis=1)` or `.idxmin(axis=1)` to find the index labels corresponding to the maximum or minimum values across rows, rather than columns.

### Finding the top *n* minimum/maximum values of a column

To find the top *n* minimum or maximum values of a column in a pandas DataFrame, you can use the `nsmallest()` and `nlargest()` methods. Here's how you can do it:

In [ ]:
# find the top 3 movies with the highest worldwide gross
top_3_movies = movie_ratings.nlargest(3, 'Worldwide Gross')
top_3_movies

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
2094,Avatar,760167650,2767891499,237000000,Dec 18 2009,PG/PG-13,Original Screenplay,Action/Adventure,Fiction,8.3,261439
2093,Titanic,600788188,1842879955,200000000,Dec 19 1997,PG/PG-13,Original Screenplay,Horror/Thriller,Fiction,7.4,240732
497,The Lord of the Rings: The Return of the King,377027325,1133027325,94000000,Dec 17 2003,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,8.8,364077

Let's double check the result using the `movie_ratings_sorted` dataframe

In [ ]:
movie_ratings_sorted['Worldwide Gross'].nlargest(3)

2094    2767891499
2093    1842879955
497     1133027325
Name: Worldwide Gross, dtype: int64

Let's find the 3 movies with the smallest IMDb votes using the `nsmallest` method

In [ ]:
bottom_3_movies = movie_ratings.nsmallest(3, 'IMDB Votes')
bottom_3_movies

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
1000,Teeth,347578,2300349,2000000,Jan 18 2008,R,Original Screenplay,Comedy,Fiction,5.5,18
1261,Birth,5005899,14603001,20000000,Oct 29 2004,R,Original Screenplay,Drama,Fiction,6.3,25
1298,CachÈ,3647381,17147381,8000000,Dec 23 2005,R,Original Screenplay,Drama,Fiction,5.5,26

Let's check the result using `sort_values` method

In [ ]:
# using the sort_values method
movie_ratings_sorted['IMDB Votes'].nsmallest(3)

1000    18
1261    25
1298    26
Name: IMDB Votes, dtype: int64

### Sub-setting data

In the chapter on reading data, we learned about different ways for subsetting data, specifically:

* Selecting columns: `df['column_name']`, `df[['col1', 'col2']]`
* Selecting rows by label: `df.loc[]`
* Selecting rows by integer position: `df.iloc[]`
* Selecting by condition (Boolean indexing): `df[df['column_name'] > value]`
* Selecting by multiple conditions: `df[(df['column_name'] > value) & (df['other_column'] == another_value)]`

## Other Manipulation

### Setting and Resetting indices

In pandas, the `index` of a dataframe can be accessed by using `index` attribute, it represents the row labels of a DataFrame. When you create a DataFrame without specifying an index, pandas automatically assigns a RangeIndex, which is a sequence of integers starting from 0.

In [42]:
# read the txt data
bestseller_data = pd.read_csv('../Data/bestseller_books.txt', sep=';')
bestseller_data.head()

,Unnamed: 0.1,Unnamed: 0,Name,Author,User Rating,Reviews,Price,Year,Genre
0,0,0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,1,1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,2,2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,3,3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,4,4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [43]:
# accessing the index of the DataFrame
bestseller_data.index

RangeIndex(start=0, stop=550, step=1)

Alternatively, we can use the `index_col` parameter in the `pd.read_csv()` function to set a specific column as the index when reading a CSV file in pandas. This allows us to directly specify which column should be used as the index of the resulting DataFrame.

In [44]:
bestseller_index_data = pd.read_csv('../Data/bestseller_books.txt', sep=';', index_col='Unnamed: 0.1')
bestseller_index_data.head()

,Unnamed: 0,Name,Author,User Rating,Reviews,Price,Year,Genre
0,0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [45]:
bestseller_index_data.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549],
      dtype='int64', length=550)

The `index` is crucial when subsetting your dataset using methods like `loc[]`, as it identifies the rows you want to select based on their labels.

In [46]:
# get the book that User rating is greater than 4.5
bestseller_index_data.loc[bestseller_index_data['User Rating']== 4.9].head()

,Unnamed: 0,Name,Author,User Rating,Reviews,Price,Year,Genre
40,40,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,14344,5,2017,Fiction
41,41,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,14344,5,2019,Fiction
81,81,Dog Man and Cat Kid: From the Creator of Capta...,Dav Pilkey,4.9,5062,6,2018,Fiction
82,82,Dog Man: A Tale of Two Kitties: From the Creat...,Dav Pilkey,4.9,4786,8,2017,Fiction
83,83,Dog Man: Brawl of the Wild: From the Creator o...,Dav Pilkey,4.9,7235,4,2018,Fiction

Additionally, you can modify the index at any point after the DataFrame is created by using the [set_index()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) function to re-index the rows based on existing column(s) of the DataFrame.

In [47]:
bestseller_data_reindexed = bestseller_data.set_index('Unnamed: 0.1')
bestseller_data_reindexed.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549],
      dtype='int64', name='Unnamed: 0.1', length=550)

Note that, the index column does not have to uniquely identify each row.  For example, if we need to subset data by `Author` frequently in our analysis, we can set it as our index

In [48]:
bestseller_author_index = bestseller_data.set_index('Author')
bestseller_author_index.loc['Jen Sincero']

,Unnamed: 0.1,Unnamed: 0,Name,User Rating,Reviews,Price,Year,Genre
Author,,,,,,,,
Jen Sincero,546,546,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,2016,Non Fiction
Jen Sincero,547,547,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,2017,Non Fiction
Jen Sincero,548,548,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,2018,Non Fiction
Jen Sincero,549,549,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,2019,Non Fiction

In [49]:
bestseller_author_index.index

Index(['JJ Smith', 'Stephen King', 'Jordan B. Peterson', 'George Orwell',
       'National Geographic Kids', 'George R. R. Martin',
       'George R. R. Martin', 'Amor Towles', 'James Comey', 'Fredrik Backman',
       ...
       'R. J. Palacio', 'R. J. Palacio', 'R. J. Palacio', 'R. J. Palacio',
       'R. J. Palacio', 'Jeff Kinney', 'Jen Sincero', 'Jen Sincero',
       'Jen Sincero', 'Jen Sincero'],
      dtype='object', name='Author', length=550)

You can revert it back to a default index using `reset_index()`. It converts the current index into a regular column and resets the index to a default integer sequence.

In [50]:
bestseller_author_index.reset_index()

,Author,Unnamed: 0.1,Unnamed: 0,Name,User Rating,Reviews,Price,Year,Genre
0,JJ Smith,0,0,10-Day Green Smoothie Cleanse,4.7,17350,8,2016,Non Fiction
1,Stephen King,1,1,11/22/63: A Novel,4.6,2052,22,2011,Fiction
2,Jordan B. Peterson,2,2,12 Rules for Life: An Antidote to Chaos,4.7,18979,15,2018,Non Fiction
3,George Orwell,3,3,1984 (Signet Classics),4.7,21424,6,2017,Fiction
4,National Geographic Kids,4,4,"5,000 Awesome Facts (About Everything!) (Natio...",4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...,...,...
545,Jeff Kinney,545,545,Wrecking Ball (Diary of a Wimpy Kid Book 14),4.9,9413,8,2019,Fiction
546,Jen Sincero,546,546,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,2016,Non Fiction
547,Jen Sincero,547,547,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,2017,Non Fiction
548,Jen Sincero,548,548,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,2018,Non Fiction
549,Jen Sincero,549,549,You Are a Badass: How to Stop Doubting Your Gr...,4.7,14331,8,2019,Non Fiction

In summary, the index is a powerful feature of pandas for organizing and accessing data, and it can be set, changed, or reset as needed to suit your data analysis.

Later, you will learn about **hierarchical indexing**, which allows you to create multi-level indices by passing multiple columns.

### Dropping a column


In pandas, you can drop a column from a DataFrame using the drop() method. This is useful when you want to remove columns that are redundant or when you want to simplify your DataFrame by excluding unnecessary data.
```
df.drop(columns='column_name')
df.drop(columns= ['col_1', 'col_2'])
```

In [52]:
# drop the repeated rows in the bestseller dataframe
bestseller_df = bestseller_index_data.drop(columns = 'Unnamed: 0')
bestseller_df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [53]:
# another way to drop the column
bestseller_index_data.drop('Unnamed: 0', axis=1).head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

**Note**: The `df.drop()` function can be used to remove rows by specifying row labels, index values, or based on conditions. It includes an `axis` parameter, which defaults to dropping rows (`axis=0`). Feel free to explore its additional options.

### Adding a column

In a DataFrame, it’s common to create new columns based on existing columns for analysis or prediction purposes. If the column name you specify does not already exist, a new column will be added to the DataFrame. If the column name already exists, the new values will overwrite the existing column.

Let's classify books based on their user rating

In [54]:
def classify_rating(rating):
    if rating >= 4.5:
        return 'Highly Rated'
    elif 3.0 <= rating < 4.5:
        return 'Moderately Rated'
    else:
        return 'Low Rated'

In [86]:
bestseller_df['Rating_Class'] = bestseller_df['User Rating'].apply(classify_rating)

bestseller_df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,rating_class,Rating_class,Rating_Class
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,Highly Rated,Highly Rated,Highly Rated
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,Highly Rated,Highly Rated,Highly Rated
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,Highly Rated,Highly Rated,Highly Rated
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,Highly Rated,Highly Rated,Highly Rated
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,Highly Rated,Highly Rated,Highly Rated

### Renaming a column

To rename a column in a pandas DataFrame, you can use the `rename()` method. .

* Renaming a single column
```
df.rename(columns={'old_name': 'new_name'}, inplace=False)
```

In [55]:
# rename Year to Publication Year
bestseller_df.rename(columns={'Year':'Publication Year'}, inplace=True)
bestseller_df.head()

,Name,Author,User Rating,Reviews,Price,Publication Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

* Renameing multiple columns

Specifying a dictionary that maps old column names to new one

```
df_renamed_multiple = df.rename(columns={'col1': 'new_col1', 'col2': 'new_col2'})
```

In [56]:
# rename Name to Book Name, and Author to Writer
bestseller_df.rename(columns={'Name':'Book Name', 'Author':'Writer'}, inplace=True)
bestseller_df.head()

,Book Name,Writer,User Rating,Reviews,Price,Publication Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

### Sorting data

Sorting dataset is a very common operation. The [sort_values()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html) function of Pandas can be used to sort a Pandas DataFrame or Series. Let us sort the spotify data in decreasing order of *track_popularity*:

In [ ]:
bestseller_sorted = bestseller_index_data.sort_values(by = 'User Rating', ascending = False)
bestseller_sorted.head()

,Unnamed: 0,Name,Author,User Rating,Reviews,Price,Year,Genre
521,521,Unfreedom of the Press,Mark R. Levin,4.9,5956,11,2019,Non Fiction
420,420,The Legend of Zelda: Hyrule Historia,Patrick Thorpe,4.9,5396,20,2013,Fiction
248,248,"Oh, the Places You'll Go!",Dr. Seuss,4.9,21834,8,2015,Fiction
247,247,"Oh, the Places You'll Go!",Dr. Seuss,4.9,21834,8,2014,Fiction
246,246,"Oh, the Places You'll Go!",Dr. Seuss,4.9,21834,8,2013,Fiction

### Ranking data

With the [rank()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rank.html) function, we can rank the observations. 

For example, let us add a new column to the bestseller data that provides the rank of the `User Rating` column:

In [60]:
bestseller_ranked = bestseller_df.copy()
bestseller_ranked['Rating_rank']=bestseller_ranked['User Rating'].rank()
bestseller_ranked.head()

,Book Name,Writer,User Rating,Reviews,Price,Publication Year,Genre,Rating_rank
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,317.5
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,211.0
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,317.5
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,317.5
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,435.0

Note the column `Rating_rank`. Why does it contain floating point numbers? Check the `rank()` documentation to find out!

## Arithematic operations within and between DataFrames

Pandas is built on top of NumPy, and for arithmetic operations, it inherits many of NumPy's powerful features. Pandas provides an intuitive and efficient way to perform arithmetic operations both within a DataFrame (on columns or rows) and between multiple DataFrames. These operations are element-wise, meaning they are applied to corresponding elements of the DataFrame or Series.

### Arithematic operations within a DataFrame

You can easily perform arithmetic operations on columns or rows within a DataFrame

* Arithmetic Between Columns

In [61]:
# Create a DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}
df = pd.DataFrame(data)

# Adding two columns
df['A_plus_B'] = df['A'] + df['B']

# Multiplying two columns
df['A_times_C'] = df['A'] * df['C']

df

   A  B  C  A_plus_B  A_times_C
0  1  4  7         5          7
1  2  5  8         7         16
2  3  6  9         9         27

* Arithmetic on Entire Rows

In [62]:
# Summing values across columns for each row
df['row_sum'] = df.sum(axis=1)
df

   A  B  C  A_plus_B  A_times_C  row_sum
0  1  4  7         5          7       24
1  2  5  8         7         16       38
2  3  6  9         9         27       54

### Arithematic operations between DataFrames

When performing operations between two DataFrames, pandas aligns the data based on both the `index` and `column labels`. If the indices or columns do not match, pandas automatically fills the missing values with NaN (not-a-number) unless a fill value is provided.

Let us create two toy DataFrames:

In [63]:
#Creating two toy DataFrames
toy_df1 = pd.DataFrame([(1,2),(3,4),(5,6)], columns=['a','b'])
toy_df2 = pd.DataFrame([(100,200),(300,400),(500,600)], columns=['a','b'])

In [64]:
#DataFrame 1
toy_df1

   a  b
0  1  2
1  3  4
2  5  6

In [65]:
#DataFrame 2
toy_df2

     a    b
0  100  200
1  300  400
2  500  600

Element by element operations between two DataFrames can be performed with the operators `+`, `-`, `*`,`/`,`**`, and `%`. Below is an example of element-by-element addition of two DataFrames:

In [66]:
# Element-by-element arithmetic addition of the two DataFrames
toy_df1 + toy_df2

     a    b
0  101  202
1  303  404
2  505  606

Note that these operations create problems when the row indices and/or column names of the two DataFrames do not match. See the example below:

In [67]:
#Creating another toy example of a DataFrame
toy_df3 = pd.DataFrame([(100,200),(300,400),(500,600)], columns=['a','b'], index=[1,2,3])
toy_df3

     a    b
1  100  200
2  300  400
3  500  600

In [68]:
#Adding DataFrames with some unmatching row indices
toy_df1 + toy_df3

       a      b
0    NaN    NaN
1  103.0  204.0
2  305.0  406.0
3    NaN    NaN

Note that the rows whose indices match between the two DataFrames are added up. The rest of the values are missing (or `NaN`) because only one of the DataFrames has that index.

As in the case of row indices, missing values will also appear in the case of unmatching column names, as shown in the example below.

In [69]:
toy_df4 = pd.DataFrame([(100,200),(300,400),(500,600)], columns=['b','c'])
toy_df4

     b    c
0  100  200
1  300  400
2  500  600

In [70]:
#Adding DataFrames with some unmatching column names
toy_df1 + toy_df4

    a    b   c
0 NaN  102 NaN
1 NaN  304 NaN
2 NaN  506 NaN

### Arithmetic Between DataFrame and Series (Broadcasting)

Pandas supports **broadcasting**, where a Series can be broadcasted to match the dimensions of a DataFrame during an arithmetic operation.

In [71]:
# Broadcasting: The row [1,2] (a Series) is added on every row in df2 
toy_df1.loc[0,:] + toy_df2

     a    b
0  101  202
1  301  402
2  501  602

Note that the `+` operator is used to add values of a Series to a DataFrame based on column names. For adding a Series to a DataFrame based on row indices, we cannot use the `+` operator. Instead, we'll need to use the `add()` function as explained below.

**Broadcasting based on row/column labels:** We can use the [add()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.add.html) function to broadcast a Series to a DataFrame. By default the Series adds based on column names, as in the case of the `+` operator.

In [72]:
# Add the first row of df1 (a Series) to every row in df2 
toy_df2.add(toy_df1.loc[0,:])

     a    b
0  101  202
1  301  402
2  501  602

For broadcasting based on row indices, we use the `axis` argument of the `add()` function.

In [73]:
# The second column of df1 (a Series) is added to every col in df2
toy_df2.add(toy_df1.loc[:,'b'],axis='index')

     a    b
0  102  202
1  304  404
2  506  606

## Advanced DataFrame Operations

Pandas provides powerful methods for applying functions to DataFrame rows, columns, or individual elements. These methods allow for flexible data transformations, making them essential for advanced data manipulation.

### `apply()`: Row-wise,  or Column-wise

The `apply()` function in pandas is used to apply a function along an axis of a DataFrame. 

* Row-wise: You can apply a function to each row using `axis=1`.
* Column-wise: You can apply a function to each column using `axis=0` (default behavior).

Let’s create a DataFrame and apply a custom function to each row.

In [81]:
# Create a DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

In [82]:
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [83]:
# Function to compute the row sum
def row_sum(row):
    return row.sum()

In [84]:
# Apply the function row-wise (axis=1)
df['Row_Sum'] = df.apply(row_sum, axis=1)
df

   A  B  C  Row_Sum
0  1  4  7       12
1  2  5  8       15
2  3  6  9       18

Let's apply the same function to each column next

In [85]:
# Apply the function column-wise (axis=0)
column_sum = df.apply(sum, axis=0)
column_sum

A           6
B          15
C          24
Row_Sum    45
dtype: int64

### `map()`: Element-wise

`map()` is typically used for element-wise transformations on a Series.

In [86]:
# write the function to compute square of a number
def square(x):
    return x ** 2

# use the map() function to apply a function element-wise
df['A_squared'] = df['A'].map(square)
df

   A  B  C  Row_Sum  A_squared
0  1  4  7       12          1
1  2  5  8       15          4
2  3  6  9       18          9

Element-wise transformation on an entire DataFrame.

In [87]:
df.map(square)

   A   B   C  Row_Sum  A_squared
0  1  16  49      144          1
1  4  25  64      225         16
2  9  36  81      324         81

When applying a function to an entire DataFrame, it's important to ensure that all columns have the same data type. Otherwise, you might encounter errors or unexpected behavior.

In [88]:
# Create a DataFrame
df_str = pd.DataFrame({
    'A': [1, 2, 3],
    'B': ['I', 'major', 'in'],
    'C': [7, 8, 9]
})
# uncomment the following line to run the code
# df_str.map(square)

### Key Differences Between `map()` and `apply()`

| Feature                | `map()`                                   | `apply()`                               |
|-----------------------|-------------------------------------------|-----------------------------------------|
| Applies to            | Both Series and DataFrame                                     | Both Series and DataFrame               |
| Functionality         | Element-wise transformations               | Can apply more complex functions (row-wise or column-wise for DataFrame) |
| Input                 | Function, dictionary, or another Series  | Function                                 |
| Use Case              | Used for simpler element-wise replacements or mappings | Used for more complex operations that can act on rows, columns, or individual elements |
| Axis Option           | N/A                                       | Can specify axis in DataFrame (row-wise or column-wise) |

#### Summary:
- `map()`: Primarily used for element-wise operations. It can take functions, dictionaries, or Series as input for substitution or transformation.
- `apply()`: Apply complex functions across rows or columns.

## `Lambda` Functions in Pandas

A lambda function is a small, anonymous function defined using the lambda keyword in Python. It can take any number of arguments but can only have one expression. In pandas, lambda functions are often used for quick and concise operations on data.

### Syntax of Lambda Functions: 


`lambda arguments: expression`


### Key Features

* **Anonymous**: Lambda functions are defined without a name.
* **Concise**: They are typically used for small, simple functions that are not reused elsewhere.
* **Single Expression**: They can only contain one expression, which is evaluated and returned.

Lambda functions are commonly used with `apply()` and `map()` to efficiently transform data in pandas, allowing for quick, inline function definitions without the need to explicitly define separate functions.

Let's use a lambda function to rewrite the `apply()` and `map()` operations from the previous example

In [89]:
df['A_squared_lamdba'] = df['A'].map(lambda x: x ** 2)
df

   A  B  C  Row_Sum  A_squared  A_squared_lamdba
0  1  4  7       12          1                 1
1  2  5  8       15          4                 4
2  3  6  9       18          9                 9

In [90]:
df_squared = df.apply(lambda x: x ** 2)
df_squared

   A   B   C  Row_Sum  A_squared  A_squared_lamdba
0  1  16  49      144          1                 1
1  4  25  64      225         16                16
2  9  36  81      324         81                81

Let's look at other examples using lambda

Example 1: adding a new column based on existing columns

In [91]:
# Create a DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# Use a lambda function to create a new column 'C' as the sum of 'A' and 'B'
df['C'] = df.apply(lambda row: row['A'] + row['B'], axis=1)
print(df)

   A  B  C
0  1  4  5
1  2  5  7
2  3  6  9

Example 2: Filter rows based on a condition

In [92]:
# Filter rows where values in column 'A' are greater than 1
filtered_df = df[df['A'].apply(lambda x: x > 1)]
print(filtered_df)

   A  B  C
1  2  5  7
2  3  6  9

## Understanding `inplace=True` and `inplace=False`

Above, we covered multiple methods that allow you to modify a DataFrame or Series. The `inplace` parameter of these methods determines whether the operation modifies the original object or returns a new object.

* `inplace=True`: Modifies the original DataFrame or Series directly and returns None. The changes are made in place, meaning the original object is altered.
* `inplace=False`: Returns a new DataFrame or Series with the modifications, leaving the original object unchanged. This is the default behavior for most methods.

**Note**: The default value for the inplace parameter is False for most methods.

Usage Example:

In [1]:
# Create a DataFrame
inplace_df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# Drop a column without modifying the original DataFrame
df_dropped = inplace_df.drop('A', axis=1)
print(df_dropped)  # New DataFrame without column 'A'
print(inplace_df)          # Original DataFrame remains unchanged

# Drop a column in place
inplace_df.drop('A', axis=1, inplace=True)
print(inplace_df)          # Original DataFrame is now modified

   B
0  4
1  5
2  6
   A  B
0  1  4
1  2  5
2  3  6
   B
0  4
1  5
2  6

## Case study
To see the application of arithematic operations on DataFrames, let us see the case study below.

**Song recommendation:** Spotify recommends songs based on songs listened by the user. Suppose you have listened to the song *drivers license*. Spotify intends to recommend you 5 songs that are *similar* to *drivers license*. Which songs should it recommend?

Let us see the available song information that can help us identify songs similar to *drivers license*. The [columns](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html) attribute of DataFrame will display all the columns names. The description of some of the column names relating to audio features is [here](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-audio-features).

In [93]:
spotify_data.columns

Index(['artist_followers', 'genres', 'artist_name', 'artist_popularity',
       'track_name', 'track_popularity', 'duration_ms', 'explicit',
       'release_year', 'danceability', 'energy', 'key', 'loudness', 'mode',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature'],
      dtype='object')

**Solution approach:** We have several features of a song. Let us find songs similar to *drivers license* in terms of *danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, time_signature* and *tempo*. Note that we are considering only audio features for simplicity.

To find the songs most similar to *drivers license*, we need to define a measure that quantifies the similarity. Let us define similarity of a song with *drivers license* as the Euclidean distance of the song from *drivers license*, where the coordinates of a song are: (danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, time_signature, tempo). Thus, similarity can be formulated as:

$$\scriptsize
Similarity_{DL-S} = \sqrt{(danceability_{DL}-danceability_{S})^2+(energy_{DL}-energy_{S})^2 +\dots + (tempo_{DL}-tempo_{S})^2}
$$

where the subscript *DL* stands for *drivers license* and *S* stands for any song. The top 5 songs with the least value of $Similarity_{DL-S}$ will be the most similar to *drivers lincense* and should be recommended.

Let us subset the columns that we need to use to compute the Euclidean distance.

In [94]:
audio_features = spotify_data[['danceability', 'energy', 'key', 'loudness','mode','speechiness',
                               'acousticness', 'instrumentalness', 'liveness','valence', 'tempo', 'time_signature']]

In [95]:
audio_features.head()

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,0.673,0.529,0,-7.226,1,0.3060,0.0769,0.000338,0.0856,0.203,161.991,4
1,0.511,0.566,6,-7.230,0,0.2000,0.3490,0.000000,0.3400,0.218,83.903,4
2,0.699,0.687,7,-3.997,0,0.1060,0.3080,0.000036,0.1210,0.499,88.933,4
3,0.708,0.690,2,-5.181,1,0.0442,0.3480,0.000000,0.2220,0.543,79.993,4
4,0.753,0.597,8,-8.469,1,0.2920,0.0477,0.000000,0.1970,0.616,76.997,4

In [96]:
#Distribution of values of audio_features
audio_features.describe()

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000
mean,0.568357,0.580633,5.240326,-9.432548,0.670928,0.111984,0.383938,0.071169,0.223756,0.552302,119.335060,3.884177
std,0.159444,0.236631,3.532546,4.449731,0.469877,0.198068,0.321142,0.209555,0.198076,0.250017,29.864219,0.458082
min,0.000000,0.000000,0.000000,-60.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.462000,0.405000,2.000000,-11.990000,0.000000,0.033200,0.070000,0.000000,0.098100,0.353000,96.099250,4.000000
50%,0.579000,0.591000,5.000000,-8.645000,1.000000,0.043100,0.325000,0.000011,0.141000,0.560000,118.002000,4.000000
75%,0.685000,0.776000,8.000000,-6.131000,1.000000,0.075300,0.671000,0.002220,0.292000,0.760000,137.929000,4.000000
max,0.988000,1.000000,11.000000,3.744000,1.000000,0.969000,0.996000,1.000000,1.000000,1.000000,243.507000,5.000000

Note that the audio features differ in terms of scale. Some features like *key* have a wide range of [0,11], while others like *danceability* have a very narrow range of [0,0.988]. If we use them directly, features like *danceability* will have a much higher influence on $Similarity_{DL-S}$ as compared to features like *key*. Assuming we wish all the features to have equal weight in quantifying a song's similarity to *drivers license*, we should scale the features, so that their values are comparable.

Let us scale the value of each column to a standard uniform distribution: $U[0,1]$.

For scaling the values of a column to $U[0,1]$, we need to subtract the minimum value of the column from each value, and divide by the range of values of the column. For example, *danceability* can be standardized as follows:

In [97]:
#Scaling danceability to U[0,1]
danceability_value_range = audio_features.danceability.max()-audio_features.danceability.min()
danceability_std = (audio_features.danceability-audio_features.danceability.min())/danceability_value_range
danceability_std

0         0.681174
1         0.517206
2         0.707490
3         0.716599
4         0.762146
            ...
243185    0.621457
243186    0.797571
243187    0.533401
243188    0.565789
243189    0.750000
Name: danceability, Length: 243190, dtype: float64

However, it will be cumbersome to repeat the above code for each audio feature. We can instead write a function that scales values of a column to $U[0,1]$, and apply the function on all the audio features.

In [98]:
#Function to scale a column to U[0,1]
def scale_uniform(x):
    return (x-x.min())/(x.max()-x.min())

We will use the Pandas function [apply()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) to apply the above function to the DataFrame `audio_features`.

In [99]:
#Scaling all audio features to U[0,1]
audio_features_scaled = audio_features.apply(scale_uniform)

The above two blocks of code can be concisely written with the `lambda` function as:

In [100]:
audio_features_scaled = audio_features.apply(lambda x: (x-x.min())/(x.max()-x.min()))

In [101]:
#All the audio features are scaled to U[0,1]
audio_features_scaled.describe()

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000,243190.000000
mean,0.575260,0.580633,0.476393,0.793290,0.670928,0.115566,0.385480,0.071169,0.223756,0.552302,0.490068,0.776835
std,0.161380,0.236631,0.321141,0.069806,0.469877,0.204405,0.322431,0.209555,0.198076,0.250017,0.122642,0.091616
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.467611,0.405000,0.181818,0.753169,0.000000,0.034262,0.070281,0.000000,0.098100,0.353000,0.394647,0.800000
50%,0.586032,0.591000,0.454545,0.805644,1.000000,0.044479,0.326305,0.000011,0.141000,0.560000,0.484594,0.800000
75%,0.693320,0.776000,0.727273,0.845083,1.000000,0.077709,0.673695,0.002220,0.292000,0.760000,0.566427,0.800000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Since we need to find the Euclidean distance from the song *drivers license*, let us find the index of the row containing features of *drivers license.*

In [102]:
#Index of the row consisting of drivers license can be found with the index attribute
drivers_license_index = spotify_data[spotify_data.track_name=='drivers license'].index[0]

Note that the object returned by the `index` attribute is of type `pandas.core.indexes.numeric.Int64Index`. The elements of this object can be retrieved like the elements of a python list. That is why the object is sliced with `[0]` to return the first element of the object. As there is only one observation with the `track_name` as *drivers license*, we sliced the first element. If there were multiple observations with `track_name` as *drivers license*, we will obtain the indices of all those observations with the `index` attribute.

In [108]:
audio_features_scaled.loc[drivers_license_index,:]

danceability        0.592105
energy              0.436000
key                 0.909091
loudness            0.803825
mode                1.000000
speechiness         0.062023
acousticness        0.723896
instrumentalness    0.000013
liveness            0.105000
valence             0.132000
tempo               0.590841
time_signature      0.800000
Name: 2398, dtype: float64

Now, we'll subtract the audio features of *drivers license* from all other songs (broadcasting):

In [109]:
#Audio features of drivers license are being subtracted from audio features of all songs by broadcasting
songs_minus_DL = audio_features_scaled-audio_features_scaled.loc[drivers_license_index,:]

Now, let us square the difference computed above. We'll use the in-built python function `pow()` to square the difference:

In [104]:
songs_minus_DL_sq = songs_minus_DL.pow(2)
songs_minus_DL_sq.head()

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,0.007933,0.008649,0.826446,0.000580,0.0,0.064398,0.418204,1.055600e-07,0.000376,0.005041,0.005535,0.0
1,0.005610,0.016900,0.132231,0.000577,1.0,0.020844,0.139498,1.716100e-10,0.055225,0.007396,0.060654,0.0
2,0.013314,0.063001,0.074380,0.005586,1.0,0.002244,0.171942,5.382400e-10,0.000256,0.134689,0.050906,0.0
3,0.015499,0.064516,0.528926,0.003154,0.0,0.000269,0.140249,1.716100e-10,0.013689,0.168921,0.068821,0.0
4,0.028914,0.025921,0.033058,0.000021,0.0,0.057274,0.456981,1.716100e-10,0.008464,0.234256,0.075428,0.0

Now, we'll sum the squares of differences from all audio features to compute the similarity of all songs to *drivers license*.

In [105]:
distance_squared = songs_minus_DL_sq.sum(axis = 1)
distance_squared.head()

0    1.337163
1    1.438935
2    1.516317
3    1.004043
4    0.920316
dtype: float64

Now, we'll sort these distances to find the top 5 songs closest to drivers's license.

In [106]:
distances_sorted = distance_squared.sort_values()
distances_sorted.head()

2398      0.000000
81844     0.008633
4397      0.011160
130789    0.015018
143744    0.015058
dtype: float64

Using the indices of the top 5 distances, we will identify the top 5 songs most similar to *drivers license*:

In [107]:
spotify_data.loc[distances_sorted.index[0:6],:]

,artist_followers,genres,artist_name,artist_popularity,track_name,track_popularity,duration_ms,explicit,release_year,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
2398,1444702,pop,Olivia Rodrigo,88,drivers license,99,242014,1,2021,0.585,...,10,-8.761,1,0.0601,0.721,0.000013,0.105,0.132,143.874,4
81844,2264501,pop,Jay Chou,74,安靜,49,334240,0,2001,0.513,...,10,-7.853,1,0.0281,0.688,0.000008,0.116,0.123,143.924,4
4397,25457,pop,Terence Lam,60,拼命無恙 in Bb major,52,241062,0,2020,0.532,...,10,-9.690,1,0.0269,0.674,0.000000,0.117,0.190,151.996,4
130789,176266,pop,Alan Tam,54,從後趕上,8,258427,0,1988,0.584,...,10,-11.889,1,0.0282,0.707,0.000002,0.107,0.124,140.147,4
143744,396326,pop & rock,Laura Branigan,64,How Am I Supposed to Live Without You,40,263320,0,1983,0.559,...,10,-8.260,1,0.0355,0.813,0.000083,0.134,0.185,139.079,4
35627,1600562,pop,Tiziano Ferro,68,Non Me Lo So Spiegare,44,240040,0,2014,0.609,...,11,-7.087,1,0.0352,0.706,0.000000,0.130,0.207,146.078,4

We can see the top 5 songs most similar to *drivers license* in the *track_name* column above. Interestingly, three of the five songs are Asian! These songs indeed sound similar to *drivers license*!

## Independent Practice:

### Practice exercise 1

#### 

Read the file *Top 10 Albums By Year.csv*. This file contains the top 10 albums for each year from 1990 to 2021. Each row corresponds to a unique album.

#### 

Print the summary statistics of the data, and answer the following questions:

1. What proportion of albums have 15 or lesser tracks? Mention a range for the proportion.
2. What is the mean length of a track (in minutes)?

####

Why is `Worldwide Sales` not included in the summary statistics table printed in the above step?

####

Update the DataFrame so that `Worldwide Sales` is included in the summary statistics table. Print the summary statistics table.

**Hint**: Sometimes it may not be possible to convert an object to numeric(). For example, the object ‘hi’ cannot be converted to a numeric() by the python compiler. To avoid getting an error, use the `errors` argument of `to_numeric()` to force such conversions to NaN (missing value).

####

Create a new column called `mean_sales_per_year` that computes the average worldwide sales per year for each album, assuming that the worldwide sales are as of 2022. Print the first 5 rows of the updated DataFrame.

####

Find the album having the highest worldwide sales per year, and its artist.

#### 
Subset the data to include only Hip-Hop albums. How many Hip_Hop albums are there?

####

Which album amongst hip-hop has the higest mean sales per year per track, and who is its artist?

### Practice exercise 2

#### 
Read the file *STAT303-1 survey for data analysis.csv*.

#### 
How many observations and variables are there in the data?

#### 
Rename all the columns of the data, except the first two columns, with the shorter names in the list `new_col_names` given below. The order of column names in the list is the same as the order in which the columns are to be renamed starting with the third column from the left.

#### 
Rename the following columns again:

1. Rename `do_you_smoke` to `smoke`.

2. Rename `are_you_an_introvert_or_extrovert` to `introvert_extrovert`.

**Hint:** Use the function [rename()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html)

#### 
Find the proportion of people going to more than 4 parties per month. Use the variable `parties_per_month`.

#### 
Among the people who go to more than 4 parties a month, what proportion of them are introverts?

#### 
Find the proportion of people in each category of the variable `how_happy`.

#### 
Among the people who go to more than 4 parties a month, what proportion of them are either `Pretty happy` or `Very happy`?

#### 
Examine the column `num_insta_followers`. Some numbers in the column contain a comma(`,`) or a tilde(`~`). Remove both these characters from the numbers in the column. 

**Hint:** You may use the function [str.replace()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html) of the Pandas Series class.

#### 
Convert the column `num_insta_followers` to numeric. Coerce the errors.

#### 
What is the mean `internet_hours_per_day` for the top 46 people in terms of number of instagram followers?

#### 
What is the mean `internet_hours_per_day` for the remaining people?

### Practice exercise 3

#### 
Use the updated dataset from Practice exercise 2.

The last four variables in the dataset are: 

1. `cant_change_math_ability`

2. `can_change_math_ability`

3. `math_is_genetic`

4. `much_effort_is_lack_of_talent`

Each of the above variables has values - `Agree` / `Disagree`. Replace `Agree` with `1` and `Disagree` with `0`.

**Hint :** You can do it with any one of the following methods:

1. Use the map() function

2. Use the apply() function with the lambda function

3. Use the replace() function


Two of the above methods avoid a `for`-loop. Which ones?