---
title: "Pandas Fundamentals"
format: 
  html:
    code-fold: false
    toc-depth: 4
jupyter: python3
---

In [26]:
#| echo: false

# import image module
from IPython.display import Image

# get the image
Image(url="./images/pandas.png",width=675)

##  Introduction to Pandas Fundamentals

In the **Reading Data** chapter, we learned how to load data files into pandas DataFrames. Now we'll dive deeper into pandas' powerful capabilities for data manipulation and analysis. 

Pandas is an essential tool in the data scientist or data analyst’s toolkit due to its ability to handle and transform data with ease and efficiency.

###  Pandas in the Data Science Ecosystem

Pandas doesn't work in isolation - it's designed to integrate seamlessly with other Python libraries:

| Library | Integration with Pandas | Purpose |
|---------|------------------------|---------|
| **NumPy** | Built on NumPy arrays | Mathematical operations and array processing |
| **Matplotlib** | Direct plotting from DataFrames | Data visualization and charts |
| **Seaborn** | Native DataFrame support | Statistical visualizations |
| **Scikit-learn** | Seamless data flow | Machine learning algorithms |
| **SciPy** | Statistical analysis | Advanced statistical functions |

###  Core Pandas Capabilities

Throughout this chapter, you'll master these essential pandas operations:

- **Filtering & Subsetting**: Extract exactly the data you need
- **Sorting & Ranking**: Organize data for analysis
- **Adding & Removing**: Modify DataFrame structure
- **Arithmetic Operations**: Perform calculations within and between DataFrames

> 💡 **Learning Path**: We'll start with fundamental concepts and progressively build toward advanced data manipulation techniques, giving you a complete toolkit for real-world data analysis.

Now let's start by importing the essential Pandas library:

In [27]:
import pandas as pd

##  Creating Pandas Series & DataFrames

There are **two primary approaches** for creating pandas data structures, each serving different purposes in your data analysis workflow:

###  **Method 1: Reading from External Data Sources**

In real-world data science, you'll typically work with data stored in external files or databases. This is the most common approach for production analysis.

**Popular Data Sources:**

| Source Type | Pandas Function | Use Case |
|-------------|----------------|----------|
| **CSV Files** | `pd.read_csv()` | Most common - structured tabular data |
| **Excel Files** | `pd.read_excel()` | Business data, reports with multiple sheets |
| **JSON Files** | `pd.read_json()` | API data, web services, nested data |
| **SQL Databases** | `pd.read_sql()` | Enterprise databases, large datasets |
| **HTML Tables** | `pd.read_html()` | Web scraping, online data tables |

> 💡 **Pro Tip**: We covered these methods extensively in the **Reading Data** chapter. If you need a refresher on loading external data, refer back to that section!

###  **Method 2: Creating from Python Data Structures**

When you need to create data programmatically or work with small datasets for testing and learning, you can build DataFrames and Series directly from Python objects.

**Benefits of this approach:**

-  **Testing & Learning**: Perfect for experimenting with pandas features
-  **Data Generation**: Create synthetic data for analysis
-  **Small Datasets**: Handle simple, manual data entry
-  **Prototyping**: Quick data structure creation for proof-of-concepts

Let's explore how to create pandas data structures from scratch!

####  Creating Series from Python Data Structures

A **Series** is pandas' 1D data structure - think of it as a smart, labeled list or array.

#####  **Method A: From a Python List**

The simplest way to create a Series is from a Python list. Pandas automatically assigns integer indices starting from 0.

In [28]:
#Defining a Pandas Series
series_example = pd.Series(['these','are','english','words'])
series_example

0      these
1        are
2    english
3      words
dtype: object

**🔍 Key Observation**: Notice the automatic integer indices (0, 1, 2, 3) on the left! 

**Custom Indexing**: You can provide meaningful labels instead of default numbers using the `index` parameter:

In [29]:
#Defining a Pandas Series with custom row labels
series_example = pd.Series(['these','are','english','words'], index = range(101,105))
series_example

101      these
102        are
103    english
104      words
dtype: object

##### **Method B: From a Python Dictionary**

Dictionaries are perfect for creating Series with **meaningful labels**. The dictionary keys automatically become the Series index, and values become the data points.

**Perfect for**: Time series data, named categories, any key-value relationships

In [30]:
# 📊 Real-world example: US GDP per capita by year (1960-2021)
# Notice some years are missing - pandas handles this gracefully!
GDP_per_capita_dict = {'1960':3007,'1961':3067,'1962':3244,'1963':3375,'1964':3574,'1965':3828,'1966':4146,'1967':4336,'1968':4696,'1970':5234,'1971':5609,'1972':6094,'1973':6726,'1974':7226,'1975':7801,'1976':8592,'1978':10565,'1979':11674, '1980':12575,'1981':13976,'1982':14434,'1983':15544,'1984':17121,'1985':18237,  '1986':19071,'1987':20039,'1988':21417,'1989':22857,'1990':23889,'1991':24342,  '1992':25419,'1993':26387,'1994':27695,'1995':28691,'1996':29968,'1997':31459,  '1998':32854,'2000':36330,'2001':37134,'2002':37998,'2003':39490,'2004':41725,  '2005':44123,'2006':46302,'2007':48050,'2008':48570,'2009':47195,'2010':48651,  '2011':50066,'2012':51784,'2013':53291,'2015':56763,'2016':57867,'2017':59915,'2018':62805, '2019':65095,'2020':63028,'2021':69288}

In [31]:
#Example 2: Creating a Pandas Series from a Dictionary
GDP_per_capita_series = pd.Series(GDP_per_capita_dict)
GDP_per_capita_series.head()

1960    3007
1961    3067
1962    3244
1963    3375
1964    3574
dtype: int64

#### Creating a DataFrame from Python Data Structures

##### **Method A: From a list of Python Dictionary**

You can create a DataFrame where keys are column names and values are lists representing column data.

In [32]:
#List of dictionary consisting of 52 playing cards of the deck
deck_list_of_dictionaries = [{'value':i, 'suit':c}
for c in ['spades', 'clubs', 'hearts', 'diamonds']
for i in range(2,15)]

In [33]:
#Example 3: Creating a Pandas DataFrame from a List of dictionaries
deck_df = pd.DataFrame(deck_list_of_dictionaries)
deck_df.head()

   value    suit
0      2  spades
1      3  spades
2      4  spades
3      5  spades
4      6  spades

##### **Method B: From a Python Dictionary**

You can create a DataFrame where keys are column names and values are lists representing column data.

In [34]:
#Example 4: Creating a Pandas DataFrame from a Dictionary
dict_data = {'A': [1, 2, 3, 4, 5],
        'B': [20, 10, 50, 40, 30],
        'C': [100, 200, 300, 400, 500]}

dict_df = pd.DataFrame(dict_data)
dict_df

   A   B    C
0  1  20  100
1  2  10  200
2  3  50  300
3  4  40  400
4  5  30  500

## Data Selection and Filtering

Now that you understand series and dataframe are two foundamental data structures in pandas, let's master the art of **extracting exactly the data you need**. Data selection and filtering are fundamental skills that you'll use in every pandas project.

### Basic Selection

####  Extracting Column(s)

The first step when working with a DataFrame is often to extract one or more columns. To do this effectively, it’s helpful to understand the internal structure of a DataFrame. Conceptually, you can think of a DataFrame as a dictionary of lists, where the keys are column names, and the values are lists or arrays containing data for the respective columns.

**Loading Our Practice Dataset**

Let's work with a real movie ratings dataset to practice our selection techniques:

In [35]:
movie_ratings = pd.read_csv('./datasets/movie_ratings.csv')
movie_ratings.head()

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
0,Opal Dreams,14443,14443,9000000,Nov 22 2006,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,468
1,Major Dundee,14873,14873,3800000,Apr 07 1965,PG/PG-13,Adapted screenplay,Western/Musical,Fiction,6.7,2588
2,The Informers,315000,315000,18000000,Apr 24 2009,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,7595
3,Buffalo Soldiers,353743,353743,15000000,Jul 25 2003,R,Adapted screenplay,Comedy,Fiction,6.9,13510
4,The Last Sin Eater,388390,388390,2200000,Feb 09 2007,PG/PG-13,Adapted screenplay,Drama,Fiction,5.7,1012


##### **Method 1: Single Column Extraction**

Each column represents a **feature** of your data. There are **two ways** to extract a single column:

**A) Bracket Notation: `df['column_name']`** (Recommended)
- ✅ Always works  
- ✅ Handles column names with spaces
- ✅ Clear and explicit

**B) Dot Notation: `df.column_name`** (Limited use)  
- ❌ Fails with spaces in column names
- ❌ Conflicts with DataFrame methods
- ✅ Shorter syntax for simple names

In [36]:
movie_ratings.Title

0                         Opal Dreams
1                        Major Dundee
2                       The Informers
3                    Buffalo Soldiers
4                  The Last Sin Eater
                    ...
2223                      King Arthur
2224                            Mulan
2225                       Robin Hood
2226    Robin Hood: Prince of Thieves
2227                       Spiceworld
Name: Title, Length: 2228, dtype: object

In [37]:
# 🧠 Understanding the DataFrame structure: 
# DataFrames work like dictionaries with enhanced features!
movie_ratings_dict = {
    'Title':  ['Opal Dreams', 'Major Dundee', 'The Informers', 'Buffalo Soldiers', 'The Last Sin Eater'],
    'US Gross':  [14443, 14873, 315000, 353743, 388390],
    'Worldwide Gross': [14443, 14873, 315000, 353743, 388390],
    'Production Budget': [9000000, 3800000, 18000000, 15000000, 2200000]
}

**Dictionary Analogy:**

Just like accessing dictionary values by key:

In [38]:
movie_ratings_dict['Title']

['Opal Dreams',
 'Major Dundee',
 'The Informers',
 'Buffalo Soldiers',
 'The Last Sin Eater']

**DataFrame Column Extraction:**

Similarly, we extract DataFrame columns by column name:

In [39]:
movie_ratings['Title']

0                         Opal Dreams
1                        Major Dundee
2                       The Informers
3                    Buffalo Soldiers
4                  The Last Sin Eater
                    ...
2223                      King Arthur
2224                            Mulan
2225                       Robin Hood
2226    Robin Hood: Prince of Thieves
2227                       Spiceworld
Name: Title, Length: 2228, dtype: object

##### **Method 2: Multiple Column Selection**

**Key Rule**: Use a **list of column names** inside the brackets:

```python
# Single column → Series
df['column']        

# Multiple columns → DataFrame  
df[['col1', 'col2']]
```

**🔍 Notice**: Double brackets `[[]]` create a list, which tells pandas you want multiple columns!

In [40]:
movie_ratings[['Title', 'US Gross', 'Worldwide Gross' ]]

                              Title   US Gross  Worldwide Gross
0                       Opal Dreams      14443            14443
1                      Major Dundee      14873            14873
2                     The Informers     315000           315000
3                  Buffalo Soldiers     353743           353743
4                The Last Sin Eater     388390           388390
...                             ...        ...              ...
2223                    King Arthur   51877963        203877963
2224                          Mulan  120620254        303500000
2225                     Robin Hood  105269730        310885538
2226  Robin Hood: Prince of Thieves  165493908        390500000
2227                     Spiceworld   29342592         56042592

[2228 rows x 3 columns]

#### Extracting Row(s) 

##### **Single Condition Filtering**

In many cases, we need to filter rows based on specific conditions or a combination of multiple conditions. Next, let’s explore how to use these conditions effectively to extract rows that meet our criteria, whether it's a single condition or multiple conditions combined

In [41]:
# extracting the rows that have IMDB Rating greater than 8
movie_ratings[movie_ratings['IMDB Rating'] > 8]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
21,"Gandhi, My Father",240425,1375194,5000000,Aug 03 2007,Other,Adapted screenplay,Drama,Non-Fiction,8.1,50881
56,Ed Wood,5828466,5828466,18000000,Sep 30 1994,R,Adapted screenplay,Comedy,Non-Fiction,8.1,74171
67,Requiem for a Dream,3635482,7390108,4500000,Oct 06 2000,Other,Adapted screenplay,Drama,Fiction,8.5,185226
164,Trainspotting,16501785,24000785,3100000,Jul 19 1996,R,Adapted screenplay,Drama,Fiction,8.2,150483
181,The Wizard of Oz,28202232,28202232,2777000,Aug 25 2039,G,Adapted screenplay,Western/Musical,Fiction,8.3,102795
...,...,...,...,...,...,...,...,...,...,...,...
2090,Finding Nemo,339714978,867894287,94000000,May 30 2003,G,Original Screenplay,Action/Adventure,Fiction,8.2,165006
2092,Toy Story 3,410640665,1046340665,200000000,Jun 18 2010,G,Original Screenplay,Action/Adventure,Fiction,8.9,67380
2094,Avatar,760167650,2767891499,237000000,Dec 18 2009,PG/PG-13,Original Screenplay,Action/Adventure,Fiction,8.3,261439
2130,Scarface,44942821,44942821,25000000,Dec 09 1983,Other,Adapted screenplay,Drama,Fiction,8.2,152262
2194,The Departed,133311000,290539042,90000000,Oct 06 2006,R,Adapted screenplay,Drama,Fiction,8.5,264148

##### **Multiple Conditions Filtering**

To combine conditions, use **logical operators**:

| Operator | Purpose | Example |
|----------|---------|---------|
| `&` | **AND** - Both conditions must be True | `(df['A'] > 5) & (df['B'] < 10)` |
| `\|` | **OR** - Either condition can be True | `(df['A'] > 5) \| (df['B'] < 10)` |
| `~` | **NOT** - Negates the condition | `~(df['A'] > 5)` |

**🚨 Critical Rule**: Always wrap each condition in **parentheses** `()` to ensure correct evaluation order!

In [42]:
# extracting the rows that have IMDB Rating greater than 8 and US Gross less than 1000000
movie_ratings[(movie_ratings['IMDB Rating'] > 8) & (movie_ratings['US Gross'] < 1000000)]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
21,"Gandhi, My Father",240425,1375194,5000000,Aug 03 2007,Other,Adapted screenplay,Drama,Non-Fiction,8.1,50881
636,Lake of Fire,25317,25317,6000000,Oct 03 2007,Other,Adapted screenplay,Documentary,Non-Fiction,8.4,1027

##### **Negating Conditions with the `~` Operator**

The tilde (`~`) is used for negating boolean conditions in pandas, making it a useful tool for excluding specific values or rows.

In some cases, we may want to extract rows that do not meet a specific condition. To accomplish this, we can use the `~` operator, which negates a condition. This operator allows us to filter data by excluding rows that satisfy a particular condition, making it a powerful tool for refining our queries. Let’s explore how to use the `~` operator to negate conditions and select rows that do not meet our criteria

In [43]:
# Excluding the rows that have IMDB Rating that equals 8 using the tilde ~
movie_ratings[~(movie_ratings['IMDB Rating'] == 8)]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
0,Opal Dreams,14443,14443,9000000,Nov 22 2006,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,468
1,Major Dundee,14873,14873,3800000,Apr 07 1965,PG/PG-13,Adapted screenplay,Western/Musical,Fiction,6.7,2588
2,The Informers,315000,315000,18000000,Apr 24 2009,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,7595
3,Buffalo Soldiers,353743,353743,15000000,Jul 25 2003,R,Adapted screenplay,Comedy,Fiction,6.9,13510
4,The Last Sin Eater,388390,388390,2200000,Feb 09 2007,PG/PG-13,Adapted screenplay,Drama,Fiction,5.7,1012
...,...,...,...,...,...,...,...,...,...,...,...
2223,King Arthur,51877963,203877963,90000000,Jul 07 2004,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.2,53106
2224,Mulan,120620254,303500000,90000000,Jun 19 1998,G,Adapted screenplay,Action/Adventure,Non-Fiction,7.2,34256
2225,Robin Hood,105269730,310885538,210000000,May 14 2010,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.9,34501
2226,Robin Hood: Prince of Thieves,165493908,390500000,50000000,Jun 14 1991,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.7,54480
2227,Spiceworld,29342592,56042592,25000000,Jan 23 1998,PG/PG-13,Adapted screenplay,Comedy,Fiction,2.9,18010

Another way to exclude rows where a column equals a certain value, you can use `!=` to create the condition.

In [44]:
# using the != operator
movie_ratings[movie_ratings['IMDB Rating'] != 8]

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
0,Opal Dreams,14443,14443,9000000,Nov 22 2006,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,468
1,Major Dundee,14873,14873,3800000,Apr 07 1965,PG/PG-13,Adapted screenplay,Western/Musical,Fiction,6.7,2588
2,The Informers,315000,315000,18000000,Apr 24 2009,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,7595
3,Buffalo Soldiers,353743,353743,15000000,Jul 25 2003,R,Adapted screenplay,Comedy,Fiction,6.9,13510
4,The Last Sin Eater,388390,388390,2200000,Feb 09 2007,PG/PG-13,Adapted screenplay,Drama,Fiction,5.7,1012
...,...,...,...,...,...,...,...,...,...,...,...
2223,King Arthur,51877963,203877963,90000000,Jul 07 2004,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.2,53106
2224,Mulan,120620254,303500000,90000000,Jun 19 1998,G,Adapted screenplay,Action/Adventure,Non-Fiction,7.2,34256
2225,Robin Hood,105269730,310885538,210000000,May 14 2010,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.9,34501
2226,Robin Hood: Prince of Thieves,165493908,390500000,50000000,Jun 14 1991,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.7,54480
2227,Spiceworld,29342592,56042592,25000000,Jan 23 1998,PG/PG-13,Adapted screenplay,Comedy,Fiction,2.9,18010

### Advanced Selection: `.loc[]` and `.iloc[]`

When you need **precise control** over both rows and columns, pandas provides two powerful indexers that let you select exactly what you need.

####  **`.loc[]` vs `.iloc[]`: The Key Difference**

| Indexer | Uses | Best For | Example |
|---------|------|----------|---------|
| **`.loc[]`** | **Labels** (names) | Human-readable selection | `df.loc['row_name', 'column_name']` |
| **`.iloc[]`** | **Positions** (numbers) | Programmatic selection | `df.iloc[0, 1]` |

**Mental Model**

Think of your DataFrame like a **spreadsheet**:
- **`.loc[]`** works like clicking on **named** rows/columns (A1, B2, etc.)
- **`.iloc[]`** works like clicking on **position** numbers (row 0, column 1, etc.)

> 💡 **Memory Tip**: 
> - **`loc`** = **L**abels/**L**ocation names
> - **`iloc`** = **i**nteger **loc**ations 

**Preparing Our Data: Sorting by IMDB Rating**

To demonstrate `.loc[]` and `.iloc[]` effectively, let's first sort our movies by rating so we can easily select the best ones:

In [45]:
movie_ratings_sorted = movie_ratings.sort_values(by = 'IMDB Rating', ascending = False)
movie_ratings_sorted.head()

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
182,The Shawshank Redemption,28241469,28241469,25000000,Sep 23 1994,R,Adapted screenplay,Drama,Fiction,9.2,519541
2084,Inception,285630280,753830280,160000000,Jul 16 2010,PG/PG-13,Original Screenplay,Horror/Thriller,Fiction,9.1,188247
790,Schindler's List,96067179,321200000,25000000,Dec 15 1993,R,Adapted screenplay,Drama,Non-Fiction,8.9,276283
1962,Pulp Fiction,107928762,212928762,8000000,Oct 14 1994,R,Original Screenplay,Drama,Fiction,8.9,417703
561,The Dark Knight,533345358,1022345358,185000000,Jul 18 2008,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,8.9,465000

#### **Using `.loc[]` - Label-Based Selection**

**Syntax**: `df.loc[row_indexer, column_indexer]`

**Key Features:**
- Uses **actual labels** (index names, column names)
- **Inclusive** of both endpoints in slicing
- Can combine with boolean conditions
- Most **intuitive** for data analysis


🎯 **Example**: Let's subset the `Title`, `Worldwide Gross`, `Production Budget`, and `IMDB Rating` of the top 3 movies using specific row indices that obtained from the above sorting table.

In [46]:
# 📍 Select specific rows by index and specific columns by name
movies_subset = movie_ratings_sorted.loc[[182, 2084, 790], ['Title', 'IMDB Rating', 'US Gross', 'Worldwide Gross', 'Production Budget']]
print("🎬 Selected movies with key financial and rating data:")
movies_subset

🎬 Selected movies with key financial and rating data:

,Title,IMDB Rating,US Gross,Worldwide Gross,Production Budget
182,The Shawshank Redemption,9.2,28241469,28241469,25000000
2084,Inception,9.1,285630280,753830280,160000000
790,Schindler's List,8.9,96067179,321200000,25000000

The `:` symbol in `.loc` is a slicing operator that represents a range or all elements in the specified dimension (rows or columns). Use `:` alone to select all rows/columns, or with start/end points to slice specific parts of the DataFrame.

In [47]:
# 📊 Select ALL rows (:) but only specific columns
movies_subset = movie_ratings_sorted.loc[:, ['Title', 'Worldwide Gross', 'Production Budget', 'IMDB Rating']]
print(" All movies with financial and rating columns only:")
movies_subset

 All movies with financial and rating columns only:

,Title,Worldwide Gross,Production Budget,IMDB Rating
182,The Shawshank Redemption,28241469,25000000,9.2
2084,Inception,753830280,160000000,9.1
790,Schindler's List,321200000,25000000,8.9
1962,Pulp Fiction,212928762,8000000,8.9
561,The Dark Knight,1022345358,185000000,8.9
...,...,...,...,...
1051,Glitter,4273372,8500000,2.0
1495,Disaster Movie,34690901,20000000,1.7
1116,Crossover,7009668,5600000,1.7
805,From Justin to Kelly,4922166,12000000,1.6
1147,Super Babies: Baby Geniuses 2,9109322,20000000,1.4

In [48]:
# 📏 Select a RANGE of rows (182 to 561) and specific columns
movies_subset = movie_ratings_sorted.loc[182:561, ['Title', 'Worldwide Gross', 'Production Budget', 'IMDB Rating']]
print("Movies from index 182 to 561 (inclusive):")
movies_subset

Movies from index 182 to 561 (inclusive):

,Title,Worldwide Gross,Production Budget,IMDB Rating
182,The Shawshank Redemption,28241469,25000000,9.2
2084,Inception,753830280,160000000,9.1
790,Schindler's List,321200000,25000000,8.9
1962,Pulp Fiction,212928762,8000000,8.9
561,The Dark Knight,1022345358,185000000,8.9

####  **Combining `.loc` with Boolean Conditions**

**Power Move**: Filter rows AND select columns simultaneously using boolean logic!

In [49]:
# extracting the rows that have IMDB Rating greater than 8 or US Gross less than 1000000, only extract the Title and IMDB Rating columns
movie_ratings[(movie_ratings['IMDB Rating'] > 8) & (movie_ratings['US Gross'] < 1000000)][['Title','IMDB Rating']]

#using loc to extract the rows that have IMDB Rating greater than 8 or US Gross less than 1000000, only extract the Title and IMDB Rating columns
movie_ratings.loc[(movie_ratings['IMDB Rating'] > 8) & (movie_ratings['US Gross'] < 1000000),['Title','IMDB Rating']]

                 Title  IMDB Rating
21   Gandhi, My Father          8.1
636       Lake of Fire          8.4

#### **Using `.iloc[]` - Position-Based Selection**

**Syntax**: `df.iloc[row_positions, column_positions]`

**Key Features:**
- Uses **integer positions** (0-based indexing like Python lists)
- **Exclusive** of end point in slicing (like Python slicing)
- Great for **systematic sampling** or **first/last N records**
- Think: "**i**nteger **loc**ation"

| Position Type | Example | Description |
|---------------|---------|-------------|
| **Single** | `df.iloc[0, 1]` | First row, second column |
| **List** | `df.iloc[[0, 2], [1, 3]]` | Specific positions |
| **Slice** | `df.iloc[0:3, 1:4]` | Range (exclusive end) |
| **All** | `df.iloc[:, :]` | All rows and columns |

**💡 Memory Tip**: iloc = **i**nteger positions, loc = **l**abel names

In [50]:
#| echo: false

# import image module
from IPython.display import Image

# get the image
Image(url="./images/pandas-iloc-loc-index-types.png",width=450)

In [51]:
# let's check  the movie_ratings_sorted DataFrame
movie_ratings_sorted.head()

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
182,The Shawshank Redemption,28241469,28241469,25000000,Sep 23 1994,R,Adapted screenplay,Drama,Fiction,9.2,519541
2084,Inception,285630280,753830280,160000000,Jul 16 2010,PG/PG-13,Original Screenplay,Horror/Thriller,Fiction,9.1,188247
790,Schindler's List,96067179,321200000,25000000,Dec 15 1993,R,Adapted screenplay,Drama,Non-Fiction,8.9,276283
1962,Pulp Fiction,107928762,212928762,8000000,Oct 14 1994,R,Original Screenplay,Drama,Fiction,8.9,417703
561,The Dark Knight,533345358,1022345358,185000000,Jul 18 2008,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,8.9,465000

After sorting, the position-based index changes, while the label-based index remains unchanged. Let’s pass the position-based index to `iloc` to retrieve the top 2 rows from the `movie_ratings_sorted` DataFrame.

In [52]:
# 🏆 Get first 2 rows by POSITION (0 and 1), all columns
top_2_movies = movie_ratings_sorted.iloc[0:2, :]
print(" Top 2 movies by position:")
top_2_movies

 Top 2 movies by position:

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
182,The Shawshank Redemption,28241469,28241469,25000000,Sep 23 1994,R,Adapted screenplay,Drama,Fiction,9.2,519541
2084,Inception,285630280,753830280,160000000,Jul 16 2010,PG/PG-13,Original Screenplay,Horror/Thriller,Fiction,9.1,188247

It is important to note that the endpoint is excluded in an `iloc` slice.

For comparison, let’s pass the same argument to loc and see what it returns.

In [53]:
# 🔍 Same range [0:2] with loc - uses LABELS, includes endpoint
loc_result = movie_ratings_sorted.loc[0:2, :]
print(" Using .loc[0:2,:] - includes rows with labels 0, 1, AND 2:")
loc_result

 Using .loc[0:2,:] - includes rows with labels 0, 1, AND 2:

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
0,Opal Dreams,14443,14443,9000000,Nov 22 2006,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,468
851,Star Trek: Generations,75671262,120000000,38000000,Nov 18 1994,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.5,26465
140,Tuck Everlasting,19161999,19344615,15000000,Oct 11 2002,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,6639
708,De-Lovely,13337299,18396382,4000000,Jun 25 2004,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,6086
705,Flyboys,13090630,14816379,60000000,Sep 22 2006,PG/PG-13,Adapted screenplay,Drama,Non-Fiction,6.5,13934
...,...,...,...,...,...,...,...,...,...,...,...
955,The Brothers Solomon,900926,900926,10000000,Sep 07 2007,R,Original Screenplay,Comedy,Fiction,5.2,6044
1637,Drumline,56398162,56398162,20000000,Dec 13 2002,PG/PG-13,Original Screenplay,Comedy,Fiction,5.2,18165
1610,Hollywood Homicide,30207785,51107785,75000000,Jun 13 2003,PG/PG-13,Original Screenplay,Action/Adventure,Fiction,5.2,16452
569,Doom,28212337,54612337,70000000,Oct 21 2005,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,39473
2,The Informers,315000,315000,18000000,Apr 24 2009,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,7595

As you can see, `:` is used in the same way as in `loc` to denote a range of the index. All rows between label indices 0 and 2, inclusive of both ends, are returned.

In [54]:
# 🎯 Select first 10 rows and specific column positions [0, 2, 3, 9]
movies_iloc_subset = movie_ratings_sorted.iloc[0:10, [0, 2, 3, 9]]
print("📋 First 10 movies with columns at positions 0, 2, 3, 9:")
movies_iloc_subset

📋 First 10 movies with columns at positions 0, 2, 3, 9:

,Title,Worldwide Gross,Production Budget,IMDB Rating
182,The Shawshank Redemption,28241469,25000000,9.2
2084,Inception,753830280,160000000,9.1
790,Schindler's List,321200000,25000000,8.9
1962,Pulp Fiction,212928762,8000000,8.9
561,The Dark Knight,1022345358,185000000,8.9
2092,Toy Story 3,1046340665,200000000,8.9
487,The Lord of the Rings: The Fellowship of the Ring,868621686,109000000,8.8
335,Fight Club,100853753,65000000,8.8
497,The Lord of the Rings: The Return of the King,1133027325,94000000,8.8
1081,C'era una volta il West,5321508,5000000,8.8

🤔 **Critical Thinking Question**: Can you use `.iloc` for conditional filtering (like `df.iloc[df['column'] > 5]`)? 

**Answer**: ❌ **No!** `.iloc` only accepts **integer positions**, not boolean conditions. For conditional filtering, you must use `.loc` or boolean indexing directly.

#### **Summary: `.loc` vs `.iloc` - Choose Your Weapon!**

| Feature | `.loc` (Label-Based) | `.iloc` (Position-Based) |
|---------|---------------------|-------------------------|
| **Uses** | 🏷️ **Labels/Names** | 🔢 **Integer Positions** |
| **Slicing** | `[start:end]` **includes** end | `[start:end]` **excludes** end |
| **Examples** | `df.loc['row_name', 'col_name']` | `df.iloc[0, 1]` |
| **Conditions** | ✅ `df.loc[df['col'] > 5]` | ❌ No boolean conditions |
| **Best For** |  **Business logic** filtering |  **Systematic** sampling |

**Mental Model**: 

- `.loc` = "Give me the data **by name/label**" 
- `.iloc` = "Give me the data **by position number**"

### Finding Extremes in pandas: Values, Labels, and Positions

#### Finding extreme values

When you need to find extreme values, pandas offers powerful methods:

| Method | Purpose | Returns |
|--------|---------|---------|
| `min()` | 📉 **Actual minimum** value | The minimum value itself |
| `max()` | 📈 **Actual maximum** value | The maximum value itself |

In [55]:
# find the max/min worldwide gross
max_gross = max(movie_ratings["Worldwide Gross"])
min_gross = min(movie_ratings["Worldwide Gross"])

print("Hignest gross:", max_gross)
print("Minimum gross:", min_gross)

Hignest gross: 2767891499
Minimum gross: 884

#### Finding extreme labels

| Method      | Purpose                           | Returns                | Use With  |
|-------------|-----------------------------------|------------------------|-----------|
| `idxmax()`  | 🏷️ **Label** of maximum           | Index label             | `.loc`    |
| `idxmin()`  | 🏷️ **Label** of minimum           | Index label             | `.loc`    |


**💡 Pro Tip**: Use `idx` methods to **locate** the extreme values, then use `.loc` to get the full row!

**`min()` / `max()` vs. `idxmin()` / `idxmax()`**

- Use **`min()` / `max()`** when you only need the **extreme value** itself.  
- Use **`idxmin()` / `idxmax()`** when you need to know **where that extreme occurs** — i.e., the **index label**, so you can fetch the corresponding row.  

```python

In [56]:
# 🎯 Find the INDEX LABELS of movies with max/min worldwide gross
max_gross_index = movie_ratings_sorted['Worldwide Gross'].idxmax()
min_gross_index = movie_ratings_sorted['Worldwide Gross'].idxmin()

print("🏆 Highest grossing movie index:", max_gross_index)
print("📉 Lowest grossing movie index:", min_gross_index)

# 🔍 Now get the full details of these movies
print("\n Highest grossing movie:")
print(movie_ratings_sorted.loc[max_gross_index, ['Title', 'Worldwide Gross']])

print("\n Lowest grossing movie:")
print(movie_ratings_sorted.loc[min_gross_index, ['Title', 'Worldwide Gross']])

🏆 Highest grossing movie index: 2094
📉 Lowest grossing movie index: 896

 Highest grossing movie:
Title                  Avatar
Worldwide Gross    2767891499
Name: 2094, dtype: object

 Lowest grossing movie:
Title              In Her Line of Fire
Worldwide Gross                    884
Name: 896, dtype: object

**Workflow**: `idxmin()`/`idxmax()` return **index labels** → use with `.loc` to extract full rows

**Example**: Find the index, then get the actual value:

In [21]:
# 💰 Get the actual gross values using the indices we found
print(" Max worldwide gross:", f"${movie_ratings_sorted.loc[max_gross_index, 'Worldwide Gross']:,.0f}")
print(" Min worldwide gross:", f"${movie_ratings_sorted.loc[min_gross_index, 'Worldwide Gross']:,.0f}")

 Max worldwide gross: $2,767,891,499
 Min worldwide gross: $884

#### Finding extreme positions

When you need **position numbers** instead of **label names**, you need to use `argmax()` and `argmin()`

| Method | Purpose | Returns | Use With |
|--------|---------|---------|-----------|
| `argmax()` | 📍 **Position** of maximum | Integer index (0-based) | `.iloc` |
| `argmin()` | 📍 **Position** of minimum | Integer index (0-based) | `.iloc` |

In [57]:
# 🎯 Find POSITIONS (not labels) of movies with max/min worldwide gross  
max_position = movie_ratings_sorted['Worldwide Gross'].argmax()
min_position = movie_ratings_sorted['Worldwide Gross'].argmin()

print("🏆 Max gross at position:", max_position)
print("📉 Min gross at position:", min_position)

# 🔍 Use iloc with positions to get the actual values
print("\n💰 Max worldwide gross:", f"${movie_ratings_sorted.iloc[max_position, 2]:,.0f}")
print("💸 Min worldwide gross:", f"${movie_ratings_sorted.iloc[min_position, 2]:,.0f}")

# 🎬 Get full movie details using positions
print("\n🎭 Movies with extreme gross values:")
print("Highest:", movie_ratings_sorted.iloc[max_position]['Title'])
print("Lowest:", movie_ratings_sorted.iloc[min_position]['Title'])

🏆 Max gross at position: 48
📉 Min gross at position: 2149

💰 Max worldwide gross: $2,767,891,499
💸 Min worldwide gross: $884

🎭 Movies with extreme gross values:
Highest: Avatar
Lowest: In Her Line of Fire

**Pro Tips for Min/Max Operations**

| Scenario | Recommended Method | Reason |
|----------|-------------------|---------|
| **Custom/Non-unique indices** | `idxmax()` / `idxmin()` | Returns meaningful labels |
| **Simple position-based work** | `argmax()` / `argmin()` | Direct integer positions |
| **Find max/min across rows** | `df.idxmax(axis=1)` | Column name with max value per row |
| **Find max/min across columns** | `df.idxmax(axis=0)` | Row index with max value per column |

**🧠 Memory Aid**: 
- `idx` → **labels** → use with `.loc`
- `arg` → **positions** → use with `.iloc`

## **Sorting & Ranking**: Organize data for analysis

###  **Why Sorting and Ranking Matter**

Sorting and ranking are fundamental operations in data analysis that help you:
-  **Identify top performers** (best movies, highest sales)
-  **Understand distributions** (from lowest to highest values)
-  **Find outliers** (extreme values at the ends)
-  **Create ordered presentations** (leaderboards, reports)


###  **Basic Sorting with `sort_values()`**

**Syntax**: `df.sort_values(by='column_name', ascending=True/False)`

| Parameter | Purpose | Options |
|-----------|---------|---------|
| `by` | Column(s) to sort by | Single column or list of columns |
| `ascending` | Sort direction | `True` (low→high), `False` (high→low) |
| `na_position` | Where to put NaN values | `'first'` or `'last'` |
| `inplace` | Modify original DataFrame | `True` or `False` |

In [58]:
# 🎬 Sort movies by IMDB Rating (ascending - lowest to highest)
movies_by_rating_asc = movie_ratings.sort_values(by='IMDB Rating', ascending=True)
print("🔥 Movies sorted by IMDB Rating (worst to best):")
print(movies_by_rating_asc[['Title', 'IMDB Rating']].head())

print("\n" + "="*50)

# 🏆 Sort movies by IMDB Rating (descending - highest to lowest)  
movies_by_rating_desc = movie_ratings.sort_values(by='IMDB Rating', ascending=False)
print("🌟 Movies sorted by IMDB Rating (best to worst):")
print(movies_by_rating_desc[['Title', 'IMDB Rating']].head())

🔥 Movies sorted by IMDB Rating (worst to best):
                              Title  IMDB Rating
1147  Super Babies: Baby Geniuses 2          1.4
805            From Justin to Kelly          1.6
1495                 Disaster Movie          1.7
1116                      Crossover          1.7
1051                        Glitter          2.0

==================================================
🌟 Movies sorted by IMDB Rating (best to worst):
                         Title  IMDB Rating
182   The Shawshank Redemption          9.2
2084                 Inception          9.1
790           Schindler's List          8.9
1962              Pulp Fiction          8.9
561            The Dark Knight          8.9

###  **Sorting by Multiple Columns**

**Real-world scenario**: Sort movies by **genre first**, then by **worldwide gross** within each genre

**Syntax**: `df.sort_values(by=['column1', 'column2'], ascending=[True, False])`

In [60]:
movie_ratings

,Title,US Gross,Worldwide Gross,Production Budget,Release Date,MPAA Rating,Source,Major Genre,Creative Type,IMDB Rating,IMDB Votes
0,Opal Dreams,14443,14443,9000000,Nov 22 2006,PG/PG-13,Adapted screenplay,Drama,Fiction,6.5,468
1,Major Dundee,14873,14873,3800000,Apr 07 1965,PG/PG-13,Adapted screenplay,Western/Musical,Fiction,6.7,2588
2,The Informers,315000,315000,18000000,Apr 24 2009,R,Adapted screenplay,Horror/Thriller,Fiction,5.2,7595
3,Buffalo Soldiers,353743,353743,15000000,Jul 25 2003,R,Adapted screenplay,Comedy,Fiction,6.9,13510
4,The Last Sin Eater,388390,388390,2200000,Feb 09 2007,PG/PG-13,Adapted screenplay,Drama,Fiction,5.7,1012
...,...,...,...,...,...,...,...,...,...,...,...
2223,King Arthur,51877963,203877963,90000000,Jul 07 2004,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.2,53106
2224,Mulan,120620254,303500000,90000000,Jun 19 1998,G,Adapted screenplay,Action/Adventure,Non-Fiction,7.2,34256
2225,Robin Hood,105269730,310885538,210000000,May 14 2010,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.9,34501
2226,Robin Hood: Prince of Thieves,165493908,390500000,50000000,Jun 14 1991,PG/PG-13,Adapted screenplay,Action/Adventure,Fiction,6.7,54480
2227,Spiceworld,29342592,56042592,25000000,Jan 23 1998,PG/PG-13,Adapted screenplay,Comedy,Fiction,2.9,18010

In [64]:
# 🎯 Multi-column sorting: Genre (A-Z), then Worldwide Gross (high to low)
movies_multi_sort = movie_ratings.sort_values(
    by=['Major Genre', 'Worldwide Gross'], 
    ascending=[True, False]  # Genre A-Z, Gross high-to-low
)

# 💡 Pro tip: Check how many unique genres we have
print(f"\n Total unique genres: {movie_ratings['Major Genre'].nunique()}")
print("🏷️ Genres:", sorted(movie_ratings['Major Genre'].unique()))

print(" Movies sorted by Major Genre (A-Z), then by Worldwide Gross (high-to-low):")
movies_multi_sort[['Major Genre', 'Title', 'Worldwide Gross']].head(10)

 Total unique genres: 6
🏷️ Genres: ['Action/Adventure', 'Comedy', 'Documentary', 'Drama', 'Horror/Thriller', 'Western/Musical']
 Movies sorted by Major Genre (A-Z), then by Worldwide Gross (high-to-low):

,Major Genre,Title,Worldwide Gross
2094,Action/Adventure,Avatar,2767891499
497,Action/Adventure,The Lord of the Rings: The Return of the King,1133027325
895,Action/Adventure,Pirates of the Caribbean: Dead Man's Chest,1065659812
2092,Action/Adventure,Toy Story 3,1046340665
496,Action/Adventure,Alice in Wonderland,1023291110
561,Action/Adventure,The Dark Knight,1022345358
495,Action/Adventure,Harry Potter and the Sorcerer's Stone,976457891
894,Action/Adventure,Pirates of the Caribbean: At World's End,960996492
494,Action/Adventure,Harry Potter and the Order of the Phoenix,938468864
493,Action/Adventure,Harry Potter and the Half-Blood Prince,937499905

###  **Ranking Methods with `rank()`**

**Purpose**: Assign numerical ranks to values (1st, 2nd, 3rd, etc.)

| Method | Handling Ties | Example (values: [1, 2, 2, 4]) |
|--------|---------------|--------------------------------|
| `'average'` | Average of tied ranks | [1.0, 2.5, 2.5, 4.0] |
| `'min'` | Minimum rank for ties | [1, 2, 2, 4] |
| `'max'` | Maximum rank for ties | [1, 3, 3, 4] |
| `'first'` | Order of appearance | [1, 2, 3, 4] |
| `'dense'` | No gaps in ranks | [1, 2, 2, 3] |

**💡 Use Cases**: Create leaderboards, percentile rankings, performance tiers

In [65]:
# 🏆 Create rankings for IMDB ratings (higher rating = better rank)
movie_ratings['Rating_Rank'] = movie_ratings['IMDB Rating'].rank(ascending=False, method='min')

# 💰 Create rankings for worldwide gross (higher gross = better rank)  
movie_ratings['Gross_Rank'] = movie_ratings['Worldwide Gross'].rank(ascending=False, method='min')

# 🎯 Show top 10 movies by IMDB rating with their ranks
top_rated = movie_ratings.nsmallest(10, 'Rating_Rank')
print("🌟 Top 10 Movies by IMDB Rating:")
print(top_rated[['Title', 'IMDB Rating', 'Rating_Rank', 'Worldwide Gross', 'Gross_Rank']].to_string(index=False))

print("\n" + "="*60)

# 💎 Compare: Movies that are highly rated vs highly grossing
print("\n🎭 Rating vs Gross Performance Analysis:")
comparison = movie_ratings[['Title', 'IMDB Rating', 'Rating_Rank', 'Worldwide Gross', 'Gross_Rank']].head(10)
print(comparison.to_string(index=False))

🌟 Top 10 Movies by IMDB Rating:
                                            Title  IMDB Rating  Rating_Rank  Worldwide Gross  Gross_Rank
                         The Shawshank Redemption          9.2          1.0         28241469      1339.0
                                        Inception          9.1          2.0        753830280        33.0
                                  The Dark Knight          8.9          3.0       1022345358         7.0
                                 Schindler's List          8.9          3.0        321200000       167.0
                                     Pulp Fiction          8.9          3.0        212928762       299.0
                                      Toy Story 3          8.9          3.0       1046340665         5.0
                                   Cidade de Deus          8.8          7.0         28763397      1328.0
                                       Fight Club          8.8          7.0        100853753       647.0
The Lord of the Rings: The Fellowship of the Ring          8.8          7.0        868621686        19.0
    The Lord of the Rings: The Return of the King          8.8          7.0       1133027325         3.0

============================================================

🎭 Rating vs Gross Performance Analysis:
                             Title  IMDB Rating  Rating_Rank  Worldwide Gross  Gross_Rank
                       Opal Dreams          6.5        994.0            14443      2223.0
                      Major Dundee          6.7        828.0            14873      2222.0
                     The Informers          5.2       1808.0           315000      2179.0
                  Buffalo Soldiers          6.9        665.0           353743      2176.0
                The Last Sin Eater          5.7       1535.0           388390      2172.0
The City of Your Final Destination          6.6        914.0           493296      2165.0
                         The Claim          6.5        994.0           622023      2154.0
                     Texas Rangers          5.0       1873.0           623374      2152.0
               Ride With the Devil          6.4       1058.0           630779      2149.0
                          Karakter          7.8        167.0           713413      2142.0

###  **Percentile Ranking**

Convert ranks to **percentiles** (0-100%) to understand relative position in the dataset

In [66]:
# 📊 Calculate percentile rankings (0-100%)
movie_ratings['Rating_Percentile'] = movie_ratings['IMDB Rating'].rank(pct=True) * 100
movie_ratings['Gross_Percentile'] = movie_ratings['Worldwide Gross'].rank(pct=True) * 100

# 🎯 Interpret percentiles
print("📈 Percentile Interpretation Guide:")
print("• 90th+ percentile = Top 10% (Excellent)")
print("• 75th+ percentile = Top 25% (Very Good)")  
print("• 50th+ percentile = Above Average")
print("• Below 50th = Below Average")

print("\n🏆 Top performers in both rating AND gross:")
top_both = movie_ratings[
    (movie_ratings['Rating_Percentile'] >= 90) & 
    (movie_ratings['Gross_Percentile'] >= 90)
][['Title', 'IMDB Rating', 'Rating_Percentile', 'Worldwide Gross', 'Gross_Percentile']]

if len(top_both) > 0:
    print(top_both.round(1).to_string(index=False))
else:
    print("🤔 No movies in top 10% for both rating AND gross!")
    
# 🎭 Show some examples with percentile context
print("\n📊 Sample movies with percentile context:")
sample = movie_ratings[['Title', 'IMDB Rating', 'Rating_Percentile', 'Worldwide Gross', 'Gross_Percentile']].head(5)
print(sample.round(1).to_string(index=False))

📈 Percentile Interpretation Guide:
• 90th+ percentile = Top 10% (Excellent)
• 75th+ percentile = Top 25% (Very Good)
• 50th+ percentile = Above Average
• Below 50th = Below Average

🏆 Top performers in both rating AND gross:
                                                 Title  IMDB Rating  Rating_Percentile  Worldwide Gross  Gross_Percentile
                                        The Green Mile          8.4               98.3        286601374              90.8
                                        Shutter Island          8.0               94.8        294512934              91.3
                   The Curious Case of Benjamin Button          8.0               94.8        329809326              92.8
                                       Jurassic Park 3          7.9               93.3        365900000              94.3
                                    Gone with the Wind          8.2               96.9        390525192              95.1
                                          The Exorcist          8.1               96.1        402500000              95.3
                                  The Bourne Ultimatum          8.2               96.9        442161562              96.0
                                                  Jaws          8.3               97.7        470700000              96.5
                                                 Shrek          8.0               94.8        484399218              96.8
                              How to Train Your Dragon          8.2               96.9        491581231              96.9
                                         Casino Royale          8.0               94.8        596365000              97.9
                                          Forrest Gump          8.6               99.1        679400525              98.3
     The Lord of the Rings: The Fellowship of the Ring          8.8               99.6        868621686              99.2
                                         Jurassic Park          7.9               93.3        923067947              99.5
                 The Lord of the Rings: The Two Towers          8.7               99.4        926284377              99.5
         The Lord of the Rings: The Return of the King          8.8               99.6       1133027325              99.9
                                         Batman Begins          8.3               97.7        372353017              94.6
                                                    X2          7.8               91.5        407711549              95.4
                                                   300          7.8               91.5        456068181              96.2
                                              Iron Man          7.9               93.3        582604126              97.7
                                       The Dark Knight          8.9               99.8       1022345358              99.7
                                      A Beautiful Mind          8.0               94.8        316708996              92.4
                              The Pursuit of Happyness          7.8               91.5        306086036              91.9
                                      Schindler's List          8.9               99.8        321200000              92.5
                                          The Fugitive          7.8               91.5        368900000              94.5
                                             Star Trek          8.2               96.9        385680447              94.9
Pirates of the Caribbean: The Curse of the Black Pearl          8.0               94.8        655011224              98.2
                                    As Good as it Gets          7.8               91.5        314111923              92.2
                                  Inglourious Basterds          8.4               98.3        320389438              92.5
                                                 Se7en          8.7               99.4        328125643              92.7
                                       American Beauty          8.6               99.1        356258047              93.6
                                             Toy Story          8.2               96.9        361948825              94.0
                                   Slumdog Millionaire          8.3               97.7        365257315              94.3
                               Raiders of the Lost Ark          8.7               99.4        386800358              95.0
                                      The Last Samurai          7.8               91.5        456810575              96.3
                                             Gladiator          8.3               97.7        457683805              96.3
                                            The Matrix          8.7               99.4        460279930              96.4
                                          The Hangover          7.9               93.3        465132119              96.5
                                   Saving Private Ryan          8.5               98.8        481635085              96.7
                                           Toy Story 2          8.0               94.8        484966906              96.8
                                               Aladdin          7.8               91.5        504050219              97.1
                            Terminator 2: Judgment Day          8.5               98.8        516816151              97.2
                                                WALL-E          8.5               98.8        532743103              97.4
                                           Ratatouille          8.1               96.1        620495432              98.0
                                       The Incredibles          8.1               96.1        632882184              98.2
                                       The Sixth Sense          8.2               96.9        672806292              98.3
                                                    Up          8.4               98.3        731304609              98.5
                                             Inception          9.1              100.0        753830280              98.6
                                         The Lion King          8.2               96.9        783839505              98.7
                             ET: The Extra-Terrestrial          7.9               93.3        792910554              98.9
                                          Finding Nemo          8.2               96.9        867894287              99.1
                                           Toy Story 3          8.9               99.8       1046340665              99.8
                                                Avatar          8.3               97.7       2767891499             100.0
                                          The Departed          8.5               98.8        290539042              91.2

📊 Sample movies with percentile context:
             Title  IMDB Rating  Rating_Percentile  Worldwide Gross  Gross_Percentile
       Opal Dreams          6.5               54.0            14443               0.3
      Major Dundee          6.7               61.0            14873               0.3
     The Informers          5.2               18.2           315000               2.2
  Buffalo Soldiers          6.9               68.4           353743               2.4
The Last Sin Eater          5.7               29.9           388390               2.6

###  **Advanced Sorting Techniques**

#### **Custom Sorting with `sort_values(key=function)`**
Apply a function to transform values before sorting

In [68]:
# 🎬 Custom sorting: Sort movie titles by length (shortest to longest)
movies_by_title_length = movie_ratings.sort_values(
    by='Title', 
    key=lambda x: x.str.len()  # Sort by title length, not alphabetically
)

print("📏 Movies sorted by title length (shortest to longest):")
title_length_sample = movies_by_title_length[['Title', 'IMDB Rating']].head(8)
for idx, row in title_length_sample.iterrows():
    print(f"📖 '{row['Title']}' ({len(row['Title'])} chars) - ⭐ {row['IMDB Rating']}")

print("\n" + "="*50)

# 🎭 Sort by absolute deviation from average rating (find most "average" movies)
avg_rating = movie_ratings['IMDB Rating'].mean()
movies_by_avg_deviation = movie_ratings.sort_values(
    by='IMDB Rating',
    key=lambda x: abs(x - avg_rating)  # Sort by distance from average
)

print(f"\n📊 Movies closest to average rating ({avg_rating:.1f}):")
avg_movies = movies_by_avg_deviation[['Title', 'IMDB Rating']].head(5)
for idx, row in avg_movies.iterrows():
    deviation = abs(row['IMDB Rating'] - avg_rating)
    print(f"🎯 '{row['Title']}' - Rating: {row['IMDB Rating']} (±{deviation:.2f} from avg)")

📏 Movies sorted by title length (shortest to longest):
📖 '9' (1 chars) - ⭐ 7.8
📖 '54' (2 chars) - ⭐ 5.6
📖 'Up' (2 chars) - ⭐ 8.4
📖 'Pi' (2 chars) - ⭐ 7.5
📖 'X2' (2 chars) - ⭐ 7.8
📖 '21' (2 chars) - ⭐ 6.7
📖 'Woo' (3 chars) - ⭐ 3.4
📖 'Saw' (3 chars) - ⭐ 7.7

==================================================

📊 Movies closest to average rating (6.2):
🎯 'Beyond Borders' - Rating: 6.2 (±0.04 from avg)
🎯 'Come Early Morning' - Rating: 6.2 (±0.04 from avg)
🎯 'Bad Boys II' - Rating: 6.2 (±0.04 from avg)
🎯 'Drop Dead Gorgeous' - Rating: 6.2 (±0.04 from avg)
🎯 'The Sisterhood of the Traveling Pants 2' - Rating: 6.2 (±0.04 from avg)

#### **Index Sorting with `sort_index()`**
Sort DataFrame by **row indices** or **column names** rather than values

In [69]:
# 📋 First, let's see the current index order
print("🔍 Current index range:")
print(f"First 5 indices: {list(movie_ratings.index[:5])}")
print(f"Last 5 indices: {list(movie_ratings.index[-5:])}")

# 🔄 Sort by index in ascending order (restore original row order)
movies_index_sorted = movie_ratings.sort_index()
print(f"\n📊 After sorting by index (ascending):")
print(f"First 5 indices: {list(movies_index_sorted.index[:5])}")

# 🔽 Sort by index in descending order
movies_index_desc = movie_ratings.sort_index(ascending=False)
print(f"\n📊 After sorting by index (descending):")
print(f"First 5 indices: {list(movies_index_desc.index[:5])}")

# 🏷️ Sort columns alphabetically by column names
print(f"\n📝 Original column order:")
print(f"Columns: {list(movie_ratings.columns)}")

movies_cols_sorted = movie_ratings.sort_index(axis=1)  # axis=1 for columns
print(f"\n🔤 Columns after alphabetical sorting:")
print(f"Columns: {list(movies_cols_sorted.columns)}")

🔍 Current index range:
First 5 indices: [0, 1, 2, 3, 4]
Last 5 indices: [2223, 2224, 2225, 2226, 2227]

📊 After sorting by index (ascending):
First 5 indices: [0, 1, 2, 3, 4]

📊 After sorting by index (descending):
First 5 indices: [2227, 2226, 2225, 2224, 2223]

📝 Original column order:
Columns: ['Title', 'US Gross', 'Worldwide Gross', 'Production Budget', 'Release Date', 'MPAA Rating', 'Source', 'Major Genre', 'Creative Type', 'IMDB Rating', 'IMDB Votes', 'Rating_Rank', 'Gross_Rank', 'Rating_Percentile', 'Gross_Percentile']

🔤 Columns after alphabetical sorting:
Columns: ['Creative Type', 'Gross_Percentile', 'Gross_Rank', 'IMDB Rating', 'IMDB Votes', 'MPAA Rating', 'Major Genre', 'Production Budget', 'Rating_Percentile', 'Rating_Rank', 'Release Date', 'Source', 'Title', 'US Gross', 'Worldwide Gross']

### **Top-N and Bottom-N Selection**

When you want the **largest or smallest N values** in a Series or DataFrame, pandas provides efficient methods that avoid a full sort:

- **`nlargest(n)`** → returns the top `n` rows with the highest values  
- **`nsmallest(n)`** → returns the bottom `n` rows with the lowest values  

These are **faster than sorting** the entire DataFrame with `.sort_values()`, especially for large datasets.

In [70]:
# 🏆 Top 5 highest-grossing movies (using nlargest)
print("💰 Top 5 Highest-Grossing Movies:")
top_gross = movie_ratings.nlargest(5, 'Worldwide Gross')[['Title', 'Worldwide Gross', 'IMDB Rating']]
for idx, row in top_gross.iterrows():
    print(f"💎 {row['Title']} - ${row['Worldwide Gross']:,.0f} (⭐ {row['IMDB Rating']})")

print("\n" + "="*50)

# 🌟 Top 5 highest-rated movies (using nlargest)
print("\n⭐ Top 5 Highest-Rated Movies:")
top_rated = movie_ratings.nlargest(5, 'IMDB Rating')[['Title', 'IMDB Rating', 'Worldwide Gross']]
for idx, row in top_rated.iterrows():
    print(f"🎭 {row['Title']} - ⭐ {row['IMDB Rating']} (${row['Worldwide Gross']:,.0f})")

print("\n" + "="*50)

# 📉 Bottom 5 lowest-rated movies (using nsmallest)
print("\n💀 Bottom 5 Lowest-Rated Movies:")
bottom_rated = movie_ratings.nsmallest(5, 'IMDB Rating')[['Title', 'IMDB Rating', 'Worldwide Gross']]
for idx, row in bottom_rated.iterrows():
    print(f"😬 {row['Title']} - ⭐ {row['IMDB Rating']} (${row['Worldwide Gross']:,.0f})")

print("\n" + "="*50)

# 💸 Bottom 5 lowest-grossing movies (using nsmallest)
print("\n💸 Bottom 5 Lowest-Grossing Movies:")
bottom_gross = movie_ratings.nsmallest(5, 'Worldwide Gross')[['Title', 'Worldwide Gross', 'IMDB Rating']]
for idx, row in bottom_gross.iterrows():
    print(f"📉 {row['Title']} - ${row['Worldwide Gross']:,.0f} (⭐ {row['IMDB Rating']})")

💰 Top 5 Highest-Grossing Movies:
💎 Avatar - $2,767,891,499 (⭐ 8.3)
💎 Titanic - $1,842,879,955 (⭐ 7.4)
💎 The Lord of the Rings: The Return of the King - $1,133,027,325 (⭐ 8.8)
💎 Pirates of the Caribbean: Dead Man's Chest - $1,065,659,812 (⭐ 7.3)
💎 Toy Story 3 - $1,046,340,665 (⭐ 8.9)

==================================================

⭐ Top 5 Highest-Rated Movies:
🎭 The Shawshank Redemption - ⭐ 9.2 ($28,241,469)
🎭 Inception - ⭐ 9.1 ($753,830,280)
🎭 The Dark Knight - ⭐ 8.9 ($1,022,345,358)
🎭 Schindler's List - ⭐ 8.9 ($321,200,000)
🎭 Pulp Fiction - ⭐ 8.9 ($212,928,762)

==================================================

💀 Bottom 5 Lowest-Rated Movies:
😬 Super Babies: Baby Geniuses 2 - ⭐ 1.4 ($9,109,322)
😬 From Justin to Kelly - ⭐ 1.6 ($4,922,166)
😬 Crossover - ⭐ 1.7 ($7,009,668)
😬 Disaster Movie - ⭐ 1.7 ($34,690,901)
😬 Son of the Mask - ⭐ 2.0 ($59,918,422)

==================================================

💸 Bottom 5 Lowest-Grossing Movies:
📉 In Her Line of Fire - $884 (⭐ 3.5)
📉 The Californians - $4,134 (⭐ 5.1)
📉 Peace, Propaganda and the Promised Land - $4,930 (⭐ 3.0)
📉 Say Uncle - $5,361 (⭐ 5.7)
📉 London - $12,667 (⭐ 7.7)

###  **Performance Comparison: Sorting Methods**

| Method | Best For | Performance | Use Case |
|--------|----------|-------------|----------|
| `sort_values()` | **Full sorting** | Slower for large data | Complete ranking, detailed analysis |
| `nlargest(n)` | **Top N only** | ⚡ **Faster** for small N | Leaderboards, top performers |
| `nsmallest(n)` | **Bottom N only** | ⚡ **Faster** for small N | Finding outliers, worst performers |
| `rank()` | **Relative positions** | Moderate | Percentiles, competition rankings |

**💡 Pro Tip**: Use `nlargest()`/`nsmallest()` when you only need the top/bottom few records!

### **Real-World Sorting Scenarios**

Let's apply sorting and ranking to solve common business questions:

In [71]:
# 🎬 Scenario 1: Find "Hidden Gems" - High rating but low gross
print("💎 HIDDEN GEMS: Great movies that didn't make much money")
print("="*55)

# Create efficiency ratio: Rating per dollar (higher = better value)
movie_ratings['Rating_per_Gross'] = movie_ratings['IMDB Rating'] / (movie_ratings['Worldwide Gross'] / 1_000_000)

hidden_gems = movie_ratings[
    (movie_ratings['IMDB Rating'] >= 7.5) & 
    (movie_ratings['Worldwide Gross'] < movie_ratings['Worldwide Gross'].median())
].nlargest(5, 'IMDB Rating')

for idx, row in hidden_gems.iterrows():
    print(f"🎭 {row['Title']}")
    print(f"   ⭐ Rating: {row['IMDB Rating']} | 💰 Gross: ${row['Worldwide Gross']:,.0f}")
    print()

print("="*55)

# 🎯 Scenario 2: Find "Blockbuster Hits" - High gross AND high rating  
print("\n🚀 BLOCKBUSTER HITS: Great movies that made tons of money")
print("="*55)

blockbusters = movie_ratings[
    (movie_ratings['IMDB Rating'] >= 7.0) & 
    (movie_ratings['Worldwide Gross'] >= movie_ratings['Worldwide Gross'].quantile(0.8))
].sort_values(['IMDB Rating', 'Worldwide Gross'], ascending=[False, False]).head(5)

for idx, row in blockbusters.iterrows():
    print(f"🏆 {row['Title']}")
    print(f"   ⭐ Rating: {row['IMDB Rating']} | 💰 Gross: ${row['Worldwide Gross']:,.0f}")
    print()

print("="*55)

# 📊 Scenario 3: ROI Analysis - Best return on investment
print("\n🎯 ROI CHAMPIONS: Best gross-to-budget ratio")
print("="*55)

# Calculate ROI ratio (avoid division by zero)
movie_ratings['ROI_Ratio'] = movie_ratings['Worldwide Gross'] / movie_ratings['Production Budget'].replace(0, 1)

top_roi = movie_ratings.nlargest(5, 'ROI_Ratio')
for idx, row in top_roi.iterrows():
    roi = row['ROI_Ratio']
    print(f"💰 {row['Title']}")
    print(f"   📈 ROI: {roi:.1f}x | Budget: ${row['Production Budget']:,.0f} → Gross: ${row['Worldwide Gross']:,.0f}")
    print()

💎 HIDDEN GEMS: Great movies that didn't make much money
=======================================================
🎭 The Shawshank Redemption
   ⭐ Rating: 9.2 | 💰 Gross: $28,241,469

🎭 Cidade de Deus
   ⭐ Rating: 8.8 | 💰 Gross: $28,763,397

🎭 C'era una volta il West
   ⭐ Rating: 8.8 | 💰 Gross: $5,321,508

🎭 The Town
   ⭐ Rating: 8.7 | 💰 Gross: $33,180,607

🎭 Memento
   ⭐ Rating: 8.7 | 💰 Gross: $39,665,950

=======================================================

🚀 BLOCKBUSTER HITS: Great movies that made tons of money
=======================================================
🏆 Inception
   ⭐ Rating: 9.1 | 💰 Gross: $753,830,280

🏆 Toy Story 3
   ⭐ Rating: 8.9 | 💰 Gross: $1,046,340,665

🏆 The Dark Knight
   ⭐ Rating: 8.9 | 💰 Gross: $1,022,345,358

🏆 Schindler's List
   ⭐ Rating: 8.9 | 💰 Gross: $321,200,000

🏆 Pulp Fiction
   ⭐ Rating: 8.9 | 💰 Gross: $212,928,762

=======================================================

🎯 ROI CHAMPIONS: Best gross-to-budget ratio
=======================================================
💰 Paranormal Activity
   📈 ROI: 12918.0x | Budget: $15,000 → Gross: $193,770,453

💰 Tarnation
   📈 ROI: 5330.3x | Budget: $218 → Gross: $1,162,014

💰 Super Size Me
   📈 ROI: 454.3x | Budget: $65,000 → Gross: $29,529,368

💰 The Brothers McMullen
   📈 ROI: 417.1x | Budget: $25,000 → Gross: $10,426,506

💰 The Blair Witch Project
   📈 ROI: 413.8x | Budget: $600,000 → Gross: $248,300,000

###*Key Takeaways: Sorting & Ranking Mastery**

**Essential Methods**

- **`sort_values()`**: Complete sorting by column values
- **`rank()`**: Assign numerical ranks (1st, 2nd, 3rd...)
- **`nlargest()` / `nsmallest()`**: Efficient top/bottom N selection  
- **`sort_index()`**: Sort by row indices or column names

**Decision Framework**

```python
# Quick reference for method selection
if "I need top/bottom N only":
    use_nlargest_or_nsmallest()
elif "I need complete ordering":
    use_sort_values()  
elif "I need relative positions":
    use_rank()
elif "I need custom ordering logic":
    use_sort_values_with_key_function()
```

**💡 Pro Tips**

1. **Performance**: `nlargest(5)` beats `sort_values().head(5)` for large datasets
2. **Multiple columns**: `sort_values(['col1', 'col2'], ascending=[True, False])`
3. **Percentiles**: `rank(pct=True) * 100` for 0-100% percentile scores
4. **Custom logic**: Use `key=lambda x: transform(x)` for complex sorting rules
5. **Stability**: pandas sorting is **stable** (preserves original order for ties)


*🎬 Next up: Learn how to manipulate and transform your sorted data!*

## **Adding & Removing**: Modify DataFrame structure

### **Why DataFrame Structure Modification Matters**

Real-world data analysis often requires:

- **Adding new columns** (calculated fields, derived metrics)
- **Removing columns** (irrelevant features, memory optimization)
- **Removing rows** (outliers, invalid data, filtering)


### **Adding Columns to DataFrames**

There are multiple ways to add new columns, each with different use cases:

#### **Method 1: Direct Assignment**
The simplest way to add a column with a constant value or calculated field. The added column will be put at the end of the dataframe

In [73]:
# 🎬 Let's work with our movie dataset to demonstrate column operations
print("Original DataFrame shape:", movie_ratings.shape)
print("Original columns:", list(movie_ratings.columns))

# 💡 Method 1a: Add a constant value column
movie_ratings['Data_Source'] = 'IMDB'
print(f"\n✅ Added constant column 'Data_Source'")

# 💡 Method 1b: Add calculated column based on existing data
movie_ratings['Profit'] = movie_ratings['Worldwide Gross'] - movie_ratings['Production Budget']
print(f"✅ Added calculated column 'Profit'")


# 📈 Show results
print(f"\n🎯 New DataFrame shape:", movie_ratings.shape)
print("🆕 Sample of new columns:")
movie_ratings[['Title', 'Profit', 'Data_Source']].head()

Original DataFrame shape: (2228, 19)
Original columns: ['Title', 'US Gross', 'Worldwide Gross', 'Production Budget', 'Release Date', 'MPAA Rating', 'Source', 'Major Genre', 'Creative Type', 'IMDB Rating', 'IMDB Votes', 'Rating_Rank', 'Gross_Rank', 'Rating_Percentile', 'Gross_Percentile', 'Rating_per_Gross', 'ROI_Ratio', 'Data_Source', 'Profit']

✅ Added constant column 'Data_Source'
✅ Added calculated column 'Profit'

🎯 New DataFrame shape: (2228, 19)
🆕 Sample of new columns:

                Title    Profit Data_Source
0         Opal Dreams  -8985557        IMDB
1        Major Dundee  -3785127        IMDB
2       The Informers -17685000        IMDB
3    Buffalo Soldiers -14646257        IMDB
4  The Last Sin Eater  -1811610        IMDB

#### **Method 3: Using `insert()` for Specific Positioning**
When you need to **control exactly where** the new column appears

In [75]:
movies_copy['Release Date']

0       Nov 22 2006
1       Apr 07 1965
2       Apr 24 2009
3       Jul 25 2003
4       Feb 09 2007
           ...
2223    Jul 07 2004
2224    Jun 19 1998
2225    May 14 2010
2226    Jun 14 1991
2227    Jan 23 1998
Name: Release Date, Length: 2228, dtype: object

In [79]:
# 🎯 Method 3: insert() for precise column positioning
# Create a working copy to demonstrate insert()
movies_copy = movie_ratings.copy()

print("📋 Original column order (first 5):")
print(list(movies_copy.columns[:5]))

# 📍 Insert a column at position 2 (after Title and Genre)
# 1) Parse the date column (e.g., "Nov 22 2006")
movies_copy["Release Date"] = pd.to_datetime(movies_copy["Release Date"], format="%b %d %Y", errors="coerce")

movies_copy.insert(2, 'Release_Decade', (movies_copy['Release Date'].dt.year // 10) * 10)

# 📍 Insert another column at the beginning (position 0)  
movies_copy.insert(0, 'Movie_ID', range(1, len(movies_copy) + 1))

print("\n New column order (first 6):")
print(list(movies_copy.columns[:6]))


# ⚠️ Note: insert() modifies the DataFrame in-place
print(f"\n DataFrame shape after inserts: {movies_copy.shape}")

print("\n Sample with positioned columns:")
movies_copy[['Movie_ID', 'Title', 'Major Genre', 'Release_Decade', 'IMDB Rating']].head()

📋 Original column order (first 5):
['Title', 'US Gross', 'Worldwide Gross', 'Production Budget', 'Release Date']

 New column order (first 6):
['Movie_ID', 'Title', 'US Gross', 'Release_Decade', 'Worldwide Gross', 'Production Budget']

 DataFrame shape after inserts: (2228, 21)

 Sample with positioned columns:

   Movie_ID               Title      Major Genre  Release_Decade  IMDB Rating
0         1         Opal Dreams            Drama            2000          6.5
1         2        Major Dundee  Western/Musical            1960          6.7
2         3       The Informers  Horror/Thriller            2000          5.2
3         4    Buffalo Soldiers           Comedy            2000          6.9
4         5  The Last Sin Eater            Drama            2000          5.7

###  **Removing Columns from DataFrames**

The most common and flexible way to remove columns is with **`.drop()`**.  

- By default, `.drop()` works on **rows**, so you need to specify `axis=1` (or `columns=`) to drop columns.  
- You can remove **one column** or **multiple columns** at the same time.  
- `.drop()` returns a **new DataFrame** unless you use `inplace=True`.

In [82]:
# 🗂️ Setup: Create a working copy with extra columns for deletion demo
movies_for_deletion = movie_ratings.copy()

# Add some temporary columns to demonstrate deletion
movies_for_deletion['Temp_Col1'] = 'Delete_Me'
movies_for_deletion['Temp_Col2'] = range(len(movies_for_deletion))
movies_for_deletion['Temp_Col3'] = movies_for_deletion['IMDB Rating'] * 2

print("📋 DataFrame before deletion:")
print(f"Shape: {movies_for_deletion.shape}")
print(f"Columns: {list(movies_for_deletion.columns)}")

# Using drop() - most common and flexible
print(f"\n Using drop()")

# Drop single column
movies_method1 = movies_for_deletion.drop('Temp_Col1', axis=1)
print(f"After dropping 1 column: {movies_method1.shape}")

# Drop multiple columns
movies_method1b = movies_for_deletion.drop(['Temp_Col1', 'Temp_Col2'], axis=1)  
print(f"After dropping 2 columns: {movies_method1b.shape}")


print(f"\n📊 Final comparison - all methods result in same shape: {movies_method1b.shape}")

📋 DataFrame before deletion:
Shape: (2228, 22)
Columns: ['Title', 'US Gross', 'Worldwide Gross', 'Production Budget', 'Release Date', 'MPAA Rating', 'Source', 'Major Genre', 'Creative Type', 'IMDB Rating', 'IMDB Votes', 'Rating_Rank', 'Gross_Rank', 'Rating_Percentile', 'Gross_Percentile', 'Rating_per_Gross', 'ROI_Ratio', 'Data_Source', 'Profit', 'Temp_Col1', 'Temp_Col2', 'Temp_Col3']

 Using drop()
After dropping 1 column: (2228, 21)
After dropping 2 columns: (2228, 20)

📊 Final comparison - all methods result in same shape: (2228, 20)

###  **Removing Rows from DataFrames**
There are several ways to remove or filter out unwanted rows in a DataFrame:

- using drop()
- boolean filtering

#### Method 1: Using `.drop()`
- Works by specifying the **row index labels** to remove.  
- Returns a new DataFrame unless you use `inplace=True`.

#### Method2: Boolean Filtering

- Keep only rows that meet a condition (the most common method in data analysis).

- More flexible than `drop()`, especially when conditions depend on column values.

In [83]:
# 🎬 Row removal demonstrations
print("📊 Original dataset info:")
print(f"Total movies: {len(movie_ratings)}")
print(f"IMDB Rating range: {movie_ratings['IMDB Rating'].min():.1f} - {movie_ratings['IMDB Rating'].max():.1f}")

# ❌ Method 1: Remove rows by index using drop()
print(f"\n🔧 Method 1: Remove specific rows by index")
movies_drop_index = movie_ratings.drop([0, 1, 2])  # Remove first 3 movies
print(f"After dropping first 3 rows: {len(movies_drop_index)} movies")

# ❌ Method 2: Remove rows by condition (Boolean filtering)
print(f"\n🔧 Method 2: Remove rows by condition")

# Remove movies with low ratings (< 5.0)
movies_no_low_rating = movie_ratings[movie_ratings['IMDB Rating'] >= 5.0]
removed_count = len(movie_ratings) - len(movies_no_low_rating)
print(f"Removed {removed_count} movies with rating < 5.0")
print(f"Remaining: {len(movies_no_low_rating)} movies")

# Remove movies with missing/zero gross
movies_with_gross = movie_ratings[movie_ratings['Worldwide Gross'] > 0]
removed_no_gross = len(movie_ratings) - len(movies_with_gross) 
print(f"Removed {removed_no_gross} movies with no gross data")
print(f"Remaining: {len(movies_with_gross)} movies")


# 📊 Summary of filtering effects
print(f"\n📈 Filtering Summary:")
print(f"Original dataset: {len(movie_ratings)} movies")
print(f"After rating filter: {len(movies_no_low_rating)} movies ({len(movies_no_low_rating)/len(movie_ratings)*100:.1f}%)")
print(f"After gross filter: {len(movies_with_gross)} movies ({len(movies_with_gross)/len(movie_ratings)*100:.1f}%)")

📊 Original dataset info:
Total movies: 2228
IMDB Rating range: 1.4 - 9.2

🔧 Method 1: Remove specific rows by index
After dropping first 3 rows: 2225 movies

🔧 Method 2: Remove rows by condition
Removed 324 movies with rating < 5.0
Remaining: 1904 movies
Removed 0 movies with no gross data
Remaining: 2228 movies

📈 Filtering Summary:
Original dataset: 2228 movies
After rating filter: 1904 movies (85.5%)
After gross filter: 2228 movies (100.0%)

### **Method Comparison Summary**

| Operation | Method | Best For | In-Place? | Performance |
|-----------|--------|----------|-----------|-------------|
| **Add Column** | `df['col'] = value` | Simple assignment | ✅ Yes | ⚡ Fastest |
| **Add Column** | `df.insert()` | Specific positioning | ✅ Yes | 🔄 Medium |
| **Remove Columns** | `df.drop()` | Flexible removal | ❌ No | ⚡ Fast |
| **Remove Rows** | Boolean filtering | Conditional removal | ❌ No | ⚡ Fast |
| **Remove Rows** | `df.drop()` | Index-based removal | ❌ No | ⚡ Fast |

##  **Arithmetic Operations**: Within and Between DataFrames

###  Why Arithmetic Operations Matter in Data Science

Arithmetic operations are fundamental to data analysis:
-  **Creating new metrics** (profit = revenue - cost)
-  **Normalizing data** (z-scores, percentages)
-  **Comparing datasets** (growth rates, ratios)
-  **Financial calculations** (ROI, margins, compound growth)
-  **Scientific computations** (formulas, transformations)

**🚀 Pandas Advantage**: intuitive!

### Arithmetic Operations Within a DataFrame

**Core Concept**: Perform calculations **between columns**, **with constants**, or **across rows**

| Operation | Symbol | Example | Business Use Case |
|-----------|--------|---------|-------------------|
| **Addition** | `+` | `df['A'] + df['B']` | Total sales = Online + Retail |
| **Subtraction** | `-` | `df['Revenue'] - df['Cost']` | Profit calculation |
| **Multiplication** | `*` | `df['Price'] * df['Quantity']` | Total value |
| **Division** | `/` | `df['Profit'] / df['Revenue']` | Margin percentage |
| **Power** | `**` | `df['Principal'] * (1 + rate)**years` | Compound interest |
| **Floor Division** | `//` | `df['Total'] // df['BatchSize']` | Number of full batches |
| **Modulo** | `%` | `df['ID'] % 10` | Grouping by last digit |

#### Column-to-Column Operations

In [88]:
# 🎯 Create a business-like DataFrame for demonstrations
business_data = {
    'Product': ['Laptop', 'Phone', 'Tablet', 'Watch', 'Headphones'],
    'Units_Sold': [150, 300, 200, 500, 250],
    'Price_per_Unit': [1200, 800, 600, 400, 200],
    'Cost_per_Unit': [800, 500, 400, 250, 120],
    'Marketing_Spend': [15000, 25000, 18000, 30000, 12000]
}
business_df = pd.DataFrame(business_data)

print("📊 Original Business Data:")
print(business_df)

# 💰 Basic arithmetic operations between columns
business_df['Total_Revenue'] = business_df['Units_Sold'] * business_df['Price_per_Unit']
business_df['Total_Cost'] = business_df['Units_Sold'] * business_df['Cost_per_Unit']  
business_df['Gross_Profit'] = business_df['Total_Revenue'] - business_df['Total_Cost']
business_df['Net_Profit'] = business_df['Gross_Profit'] - business_df['Marketing_Spend']

# 📈 Calculate ratios and percentages
business_df['Profit_Margin'] = (business_df['Gross_Profit'] / business_df['Total_Revenue']) * 100
business_df['ROI'] = (business_df['Net_Profit'] / business_df['Marketing_Spend']) * 100

print("\n💡 Enhanced Business Data with Calculations:")
print(business_df[['Product', 'Total_Revenue', 'Gross_Profit', 'Net_Profit', 'Profit_Margin', 'ROI']].round(2))

📊 Original Business Data:
      Product  Units_Sold  Price_per_Unit  Cost_per_Unit  Marketing_Spend
0      Laptop         150            1200            800            15000
1       Phone         300             800            500            25000
2      Tablet         200             600            400            18000
3       Watch         500             400            250            30000
4  Headphones         250             200            120            12000

💡 Enhanced Business Data with Calculations:
      Product  Total_Revenue  Gross_Profit  Net_Profit  Profit_Margin     ROI
0      Laptop         180000         60000       45000          33.33  300.00
1       Phone         240000         90000       65000          37.50  260.00
2      Tablet         120000         40000       22000          33.33  122.22
3       Watch         200000         75000       45000          37.50  150.00
4  Headphones          50000         20000        8000          40.00   66.67

#### Operations with Constants and Scalars

In [89]:
# 🎯 Operations with constants (scalars)
print("Operations with Constants:")

# Apply 10% discount to all prices
business_df['Discounted_Price'] = business_df['Price_per_Unit'] * 0.9

# Add fixed shipping cost of $50 to all products
business_df['Price_with_Shipping'] = business_df['Price_per_Unit'] + 50

# Calculate tax (8% of revenue)
business_df['Tax_Amount'] = business_df['Total_Revenue'] * 0.08

# Square the units sold (for some statistical analysis)
business_df['Units_Squared'] = business_df['Units_Sold'] ** 2

print("Sample with scalar operations:")
sample_cols = ['Product', 'Price_per_Unit', 'Discounted_Price', 'Price_with_Shipping', 'Tax_Amount']
print(business_df[sample_cols].head(3).to_string(index=False))

Operations with Constants:
Sample with scalar operations:
Product  Price_per_Unit  Discounted_Price  Price_with_Shipping  Tax_Amount
 Laptop            1200            1080.0                 1250     14400.0
  Phone             800             720.0                  850     19200.0
 Tablet             600             540.0                  650      9600.0

#### Row-wise Operations (Across Columns)

By default, methods like `.mean()`, `.max()`, and `.min()` operate **down each column** (`axis=0`).  
However, if you need to perform calculations **across all columns in each row**, set `axis=1`.

In [91]:
# 📊 Row-wise arithmetic operations (axis=1 for across columns)
print("🔄 Row-wise Operations:")

# Create a sample DataFrame with numerical data
sample_data = {
    'Q1_Sales': [100, 150, 200, 120, 180],
    'Q2_Sales': [110, 140, 220, 130, 190], 
    'Q3_Sales': [120, 160, 210, 140, 200],
    'Q4_Sales': [130, 170, 230, 150, 210]
}
quarterly_sales = pd.DataFrame(sample_data, 
                              index=['Product_A', 'Product_B', 'Product_C', 'Product_D', 'Product_E'])

print("📈 Quarterly Sales Data:")
print(quarterly_sales)

# Calculate row-wise statistics
quarterly_sales['Total_Sales'] = quarterly_sales.sum(axis=1)  # Sum across columns
quarterly_sales['Average_Sales'] = quarterly_sales[['Q1_Sales', 'Q2_Sales', 'Q3_Sales', 'Q4_Sales']].mean(axis=1)
quarterly_sales['Max_Quarter'] = quarterly_sales[['Q1_Sales', 'Q2_Sales', 'Q3_Sales', 'Q4_Sales']].max(axis=1)
quarterly_sales['Sales_Range'] = quarterly_sales[['Q1_Sales', 'Q2_Sales', 'Q3_Sales', 'Q4_Sales']].max(axis=1) - quarterly_sales[['Q1_Sales', 'Q2_Sales', 'Q3_Sales', 'Q4_Sales']].min(axis=1)

print("\n📊 With Row-wise Calculations:")
print(quarterly_sales.round(2))

🔄 Row-wise Operations:
📈 Quarterly Sales Data:
           Q1_Sales  Q2_Sales  Q3_Sales  Q4_Sales
Product_A       100       110       120       130
Product_B       150       140       160       170
Product_C       200       220       210       230
Product_D       120       130       140       150
Product_E       180       190       200       210

📊 With Row-wise Calculations:
           Q1_Sales  Q2_Sales  Q3_Sales  Q4_Sales  Total_Sales  Average_Sales  \
Product_A       100       110       120       130          460          115.0
Product_B       150       140       160       170          620          155.0
Product_C       200       220       210       230          860          215.0
Product_D       120       130       140       150          540          135.0
Product_E       180       190       200       210          780          195.0

           Max_Quarter  Sales_Range
Product_A          130           30
Product_B          170           30
Product_C          230           30
Product_D          150           30
Product_E          210           30

###  Arithmetic Operations Between DataFrames

**Key Concept**: When operating on **two DataFrames**, pandas **automatically aligns** data by **index** and **column labels**.

#### Alignment Behavior

| Scenario | Result | Example |
|----------|---------|---------|
| **Exact match** | Normal operation | `df1 + df2` |
| **Missing index/column** | Fills with `NaN` | Automatic alignment |
| **Different shapes** | Broadcasts when possible | Scalar operations |
| **Using fill_value** | Replaces NaN with specified value | `df1.add(df2, fill_value=0)` |

**💡 Pro Tip**: Use **explicit methods** (`add()`, `sub()`, `mul()`, `div()`) for better control over missing data!

#### Basic DataFrame-to-DataFrame Operations

In [92]:
# 🏢 Create two related business DataFrames for comparison
print("🔀 DataFrame-to-DataFrame Operations:")

# 📊 Store A performance data
store_a_data = {
    'Electronics': [50000, 55000, 60000],
    'Clothing': [30000, 32000, 35000],
    'Books': [8000, 8500, 9000]
}
store_a = pd.DataFrame(store_a_data, index=['Q1', 'Q2', 'Q3'])

# 📊 Store B performance data  
store_b_data = {
    'Electronics': [45000, 50000, 58000],
    'Clothing': [28000, 30000, 33000],
    'Books': [7500, 8000, 8800]
}
store_b = pd.DataFrame(store_b_data, index=['Q1', 'Q2', 'Q3'])

print("🏪 Store A Sales:")
print(store_a)
print("\n🏪 Store B Sales:")
print(store_b)

# 📈 Basic arithmetic operations between DataFrames
print("\n💡 Arithmetic Operations Between Stores:")

# Total sales across both stores
total_sales = store_a + store_b
print("\n📊 Combined Sales (A + B):")
print(total_sales)

# Difference in performance
sales_diff = store_a - store_b  
print("\n📊 Sales Difference (A - B):")
print(sales_diff)

# Growth ratio (Store A relative to Store B)
growth_ratio = store_a / store_b
print("\n📊 Performance Ratio (A / B):")
print(growth_ratio.round(3))

🔀 DataFrame-to-DataFrame Operations:
🏪 Store A Sales:
    Electronics  Clothing  Books
Q1        50000     30000   8000
Q2        55000     32000   8500
Q3        60000     35000   9000

🏪 Store B Sales:
    Electronics  Clothing  Books
Q1        45000     28000   7500
Q2        50000     30000   8000
Q3        58000     33000   8800

💡 Arithmetic Operations Between Stores:

📊 Combined Sales (A + B):
    Electronics  Clothing  Books
Q1        95000     58000  15500
Q2       105000     62000  16500
Q3       118000     68000  17800

📊 Sales Difference (A - B):
    Electronics  Clothing  Books
Q1         5000      2000    500
Q2         5000      2000    500
Q3         2000      2000    200

📊 Performance Ratio (A / B):
    Electronics  Clothing  Books
Q1        1.111     1.071  1.067
Q2        1.100     1.067  1.062
Q3        1.034     1.061  1.023

#### Handling Misaligned Data

In [94]:
# 🚨 Demonstrate alignment issues and solutions
print("⚠️ Handling Misaligned DataFrames:")

# Create DataFrames with different indices and columns
df1_partial = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60]
}, index=[0, 1, 2])

df2_partial = pd.DataFrame({
    'B': [5, 10, 15, 20],  # Extra row
    'C': [100, 200, 300, 400]  # Different column
}, index=[1, 2, 3, 4])  # Different indices

print("📊 DataFrame 1:")
print(df1_partial)
print("\n📊 DataFrame 2:")  
print(df2_partial)

# 🔄 Default behavior - creates NaN for missing alignments
print("\n❌ Default Addition (creates NaN):")
result_nan = df1_partial + df2_partial
print(result_nan)

# 🔧 Using explicit methods with fill_value to handle NaN
print("\n✅ Addition with fill_value=0:")
result_filled = df1_partial.add(df2_partial, fill_value=0)
print(result_filled)

# 🎯 Other explicit arithmetic methods
print("\n🔧 Explicit Methods Available:")
print("• add() - Addition with fill_value option")
print("• sub() - Subtraction with fill_value option")  
print("• mul() - Multiplication with fill_value option")
print("• div() - Division with fill_value option")

# Example with subtraction
result_sub = df1_partial.sub(df2_partial, fill_value=1)
print("\n➖ Subtraction with fill_value=1:")
print(result_sub)

⚠️ Handling Misaligned DataFrames:
📊 DataFrame 1:
    A   B
0  10  40
1  20  50
2  30  60

📊 DataFrame 2:
    B    C
1   5  100
2  10  200
3  15  300
4  20  400

❌ Default Addition (creates NaN):
    A     B   C
0 NaN   NaN NaN
1 NaN  55.0 NaN
2 NaN  70.0 NaN
3 NaN   NaN NaN
4 NaN   NaN NaN

✅ Addition with fill_value=0:
      A     B      C
0  10.0  40.0    NaN
1  20.0  55.0  100.0
2  30.0  70.0  200.0
3   NaN  15.0  300.0
4   NaN  20.0  400.0

🔧 Explicit Methods Available:
• add() - Addition with fill_value option
• sub() - Subtraction with fill_value option
• mul() - Multiplication with fill_value option
• div() - Division with fill_value option

➖ Subtraction with fill_value=1:
      A     B      C
0   9.0  39.0    NaN
1  19.0  45.0  -99.0
2  29.0  50.0 -199.0
3   NaN -14.0 -299.0
4   NaN -19.0 -399.0

###  Advanced Arithmetic Techniques

#### Broadcasting and Shape Compatibility

In [95]:
# 📐 Broadcasting: Operations between different shapes
print("📐 Broadcasting Examples:")

# DataFrame with different dimensions
sales_matrix = pd.DataFrame({
    'Jan': [1000, 1500, 2000],
    'Feb': [1100, 1600, 2100], 
    'Mar': [1200, 1700, 2200]
}, index=['Store_A', 'Store_B', 'Store_C'])

# Series for operations
monthly_bonus = pd.Series([100, 150, 200], index=['Jan', 'Feb', 'Mar'])  # Column-wise
store_multiplier = pd.Series([1.1, 1.2, 1.05], index=['Store_A', 'Store_B', 'Store_C'])  # Row-wise

print("📊 Original Sales Matrix:")
print(sales_matrix)
print("\n💰 Monthly Bonus (Series):")
print(monthly_bonus)
print("\n📈 Store Multiplier (Series):")
print(store_multiplier)

# 🔄 Broadcasting operations
print("\n✨ Broadcasting Results:")

# Add monthly bonus to each column
sales_with_bonus = sales_matrix + monthly_bonus
print("📊 Sales + Monthly Bonus (broadcasting across columns):")
print(sales_with_bonus)

# Multiply each row by store multiplier
sales_adjusted = sales_matrix.mul(store_multiplier, axis=0)  # axis=0 for row-wise
print("\n📊 Sales × Store Multiplier (broadcasting across rows):")
print(sales_adjusted.round(0))

📐 Broadcasting Examples:
📊 Original Sales Matrix:
          Jan   Feb   Mar
Store_A  1000  1100  1200
Store_B  1500  1600  1700
Store_C  2000  2100  2200

💰 Monthly Bonus (Series):
Jan    100
Feb    150
Mar    200
dtype: int64

📈 Store Multiplier (Series):
Store_A    1.10
Store_B    1.20
Store_C    1.05
dtype: float64

✨ Broadcasting Results:
📊 Sales + Monthly Bonus (broadcasting across columns):
          Jan   Feb   Mar
Store_A  1100  1250  1400
Store_B  1600  1750  1900
Store_C  2100  2250  2400

📊 Sales × Store Multiplier (broadcasting across rows):
            Jan     Feb     Mar
Store_A  1100.0  1210.0  1320.0
Store_B  1800.0  1920.0  2040.0
Store_C  2100.0  2205.0  2310.0

### Error Handling and Edge Cases

Common issues and solutions when working with arithmetic operations

In [96]:
# 🚨 Handling common arithmetic errors and edge cases
print("🛡️ Error Handling and Edge Cases:")

# Create data with potential issues
problematic_data = pd.DataFrame({
    'Values': [10, 0, -5, None, float('inf')],
    'Divisors': [2, 0, 1, 3, 2],
    'Mixed_Types': ['10', 20, '30', 40, '50']  # Mixed string/numeric
})

print("⚠️ Problematic Data:")
print(problematic_data)
print(f"Data types:\n{problematic_data.dtypes}")

# 🔧 Issue 1: Division by zero
print("\n❌ Division by Zero Issue:")
try:
    result = problematic_data['Values'] / problematic_data['Divisors']
    print("Result with division by zero:")
    print(result)
except Exception as e:
    print(f"Error: {e}")

# ✅ Solution: Handle division by zero
print("\n✅ Safe Division:")
safe_division = problematic_data['Values'].div(problematic_data['Divisors']).replace([float('inf'), float('-inf')], 0)
print(safe_division)

# 🔧 Issue 2: Mixed data types
print("\n❌ Mixed Data Types Issue:")
try:
    # Convert string column to numeric first
    mixed_numeric = pd.to_numeric(problematic_data['Mixed_Types'], errors='coerce')
    print("Converted mixed types:")
    print(mixed_numeric)
    
    # Now arithmetic works
    result = mixed_numeric + 5
    print("After adding 5:")
    print(result)
except Exception as e:
    print(f"Error: {e}")

# 🔧 Issue 3: NaN and infinity handling
print("\n🔧 NaN and Infinity Handling:")

# Create data with NaN and inf
test_data = pd.Series([1, 2, None, float('inf'), float('-inf'), 5])
print("Original data with NaN and infinity:")
print(test_data)

# Fill NaN with specific values
filled_data = test_data.fillna(0)
print("\nAfter filling NaN with 0:")
print(filled_data)

# Replace infinity with finite values
clean_data = filled_data.replace([float('inf'), float('-inf')], [999999, -999999])
print("\nAfter replacing infinity:")
print(clean_data)

# 🎯 Best practices summary
print("\n💡 Best Practices for Robust Arithmetic:")
print("1. Check data types before operations: df.dtypes")
print("2. Handle NaN values: fillna(), dropna(), or errors='coerce'")
print("3. Check for infinity: df.replace([inf, -inf], value)")
print("4. Use explicit methods for better control: add(), sub(), mul(), div()")
print("5. Validate results: df.isna().sum(), df.isinf().sum() if hasattr(df, 'isinf')")

🛡️ Error Handling and Edge Cases:
⚠️ Problematic Data:
   Values  Divisors Mixed_Types
0    10.0         2          10
1     0.0         0          20
2    -5.0         1          30
3     NaN         3          40
4     inf         2          50
Data types:
Values         float64
Divisors         int64
Mixed_Types     object
dtype: object

❌ Division by Zero Issue:
Result with division by zero:
0    5.0
1    NaN
2   -5.0
3    NaN
4    inf
dtype: float64

✅ Safe Division:
0    5.0
1    NaN
2   -5.0
3    NaN
4    0.0
dtype: float64

❌ Mixed Data Types Issue:
Converted mixed types:
0    10
1    20
2    30
3    40
4    50
Name: Mixed_Types, dtype: int64
After adding 5:
0    15
1    25
2    35
3    45
4    55
Name: Mixed_Types, dtype: int64

🔧 NaN and Infinity Handling:
Original data with NaN and infinity:
0    1.0
1    2.0
2    NaN
3    inf
4   -inf
5    5.0
dtype: float64

After filling NaN with 0:
0    1.0
1    2.0
2    0.0
3    inf
4   -inf
5    5.0
dtype: float64

After replacing infinity:
0         1.0
1         2.0
2         0.0
3    999999.0
4   -999999.0
5         5.0
dtype: float64

💡 Best Practices for Robust Arithmetic:
1. Check data types before operations: df.dtypes
2. Handle NaN values: fillna(), dropna(), or errors='coerce'
3. Check for infinity: df.replace([inf, -inf], value)
4. Use explicit methods for better control: add(), sub(), mul(), div()
5. Validate results: df.isna().sum(), df.isinf().sum() if hasattr(df, 'isinf')

###  Performance and Method Comparison

| Operation Type | Operator | Explicit Method | Fill Value | Performance | Use Case |
|----------------|----------|-----------------|------------|-------------|----------|
| **Addition** | `df1 + df2` | `df1.add(df2, fill_value=0)` | ✅ Yes | ⚡ Fast | Missing data control |
| **Subtraction** | `df1 - df2` | `df1.sub(df2, fill_value=0)` | ✅ Yes | ⚡ Fast | Missing data control |
| **Multiplication** | `df1 * df2` | `df1.mul(df2, fill_value=1)` | ✅ Yes | ⚡ Fast | Broadcasting control |
| **Division** | `df1 / df2` | `df1.div(df2, fill_value=1)` | ✅ Yes | ⚡ Fast | Zero division safety |
| **Power** | `df1 ** 2` | `df1.pow(2)` | ❌ No | 🔄 Medium | Exponential operations |
| **Floor Division** | `df1 // df2` | `df1.floordiv(df2)` | ❌ No | 🔄 Medium | Integer division |
| **Modulo** | `df1 % df2` | `df1.mod(df2)` | ❌ No | 🔄 Medium | Remainder operations |

##  Understanding `inplace=True` vs `inplace=False`

###  Why This Matters: Memory, Performance, and Safety

The `inplace` parameter is one of the **most important concepts** in pandas for:
-  **Memory management** (avoid unnecessary copies)
-  **Data integrity** (prevent accidental modifications)
-  **Performance optimization** (reduce overhead)
-  **Debugging** (track data transformations)



###  Core Concept: Modify vs Create

| Parameter | Behavior | Memory | Original Data | Return Value | Use Case |
|-----------|----------|--------|---------------|--------------|----------|
| **`inplace=False`** | 🆕 **Creates new copy** | 📈 Higher usage | ✅ **Unchanged** | Modified DataFrame | **Safe exploration** |
| **`inplace=True`** | 🔄 **Modifies original** | 📉 Lower usage | ❌ **Changed permanently** | `None` | **Final transformations** |

**🚨 Critical Rule**: `inplace=True` returns `None`, not the modified DataFrame!

In [ ]:
# 🎯 Comprehensive inplace demonstration
print("🔄 INPLACE PARAMETER DEMONSTRATION")
print("="*50)

# 📊 Create sample business data
original_data = pd.DataFrame({
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eva'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [75000, 65000, 80000, 70000, 68000],
    'Years_Experience': [5, 3, 7, 4, 6]
})

print("📋 Original DataFrame:")
print(original_data)
print(f"📍 DataFrame ID: {id(original_data)}")  # Memory address

# 🆕 Method 1: inplace=False (DEFAULT)
print(f"\n🔧 Method 1: inplace=False (Creates New Copy)")
print("-" * 45)

# Add bonus column without modifying original
df_with_bonus = original_data.assign(Bonus=original_data['Salary'] * 0.1)
print("✅ New DataFrame with bonus:")
print(df_with_bonus[['Name', 'Salary', 'Bonus']].head(3))
print(f"📍 New DataFrame ID: {id(df_with_bonus)}")

print(f"\n🔍 Original DataFrame (unchanged):")
print(original_data.head(3))
print(f"📍 Original ID still: {id(original_data)}")

# 🔄 Method 2: inplace=True (Modifies Original)
print(f"\n🔧 Method 2: inplace=True (Modifies Original)")  
print("-" * 45)

# Store original ID for comparison
original_id = id(original_data)

# Add bonus column in place
original_data['Bonus'] = original_data['Salary'] * 0.1
print("✅ Original DataFrame after in-place modification:")
print(original_data[['Name', 'Salary', 'Bonus']].head(3))
print(f"📍 Same DataFrame ID: {id(original_data)}")
print(f"🔍 ID unchanged: {original_id == id(original_data)}")

   B
0  4
1  5
2  6
   A  B
0  1  4
1  2  5
2  3  6
   B
0  4
1  5
2  6

### Common Methods Supporting `inplace` Parameter

In [97]:
# 📋 Demonstrate inplace with different pandas methods
print("🛠️ METHODS SUPPORTING INPLACE PARAMETER")
print("="*50)

# Create sample dataset for demonstrations
sample_df = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet', 'Phone', 'Laptop'],
    'Price': [1200, 800, 600, 850, 1100],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics'],
    'Stock': [10, 0, 15, 8, 12]
})

print("📊 Sample Dataset:")
print(sample_df)

# 🗑️ 1. DROP operations
print(f"\n🗑️ 1. DROP OPERATIONS")
print("-" * 30)

# Drop with inplace=False (default)
df_copy = sample_df.copy()
result = df_copy.drop('Category', axis=1)  # inplace=False by default
print("✅ After drop(inplace=False) - returns new DataFrame:")
print(f"Original shape: {df_copy.shape}, New shape: {result.shape}")

# Drop with inplace=True  
df_copy2 = sample_df.copy()
return_value = df_copy2.drop('Category', axis=1, inplace=True)
print(f"✅ After drop(inplace=True) - modifies original:")
print(f"Modified shape: {df_copy2.shape}, Return value: {return_value}")

# 🏷️ 2. RENAME operations
print(f"\n🏷️ 2. RENAME OPERATIONS")
print("-" * 30)

df_copy3 = sample_df.copy()
# Rename with inplace=False
renamed = df_copy3.rename(columns={'Product': 'Item_Name'})
print(f"✅ rename(inplace=False): Original columns unchanged")
print(f"Original: {list(df_copy3.columns)}")
print(f"New: {list(renamed.columns)}")

# Rename with inplace=True
df_copy3.rename(columns={'Product': 'Item_Name'}, inplace=True)
print(f"✅ rename(inplace=True): Original columns changed")
print(f"Modified: {list(df_copy3.columns)}")

# 🔄 3. SORT operations
print(f"\n🔄 3. SORT OPERATIONS")
print("-" * 30)

df_copy4 = sample_df.copy()
# Sort with inplace=False
sorted_df = df_copy4.sort_values('Price')
print(f"✅ sort_values(inplace=False):")
print(f"Original order preserved: {list(df_copy4['Price'])}")
print(f"New sorted order: {list(sorted_df['Price'])}")

# Sort with inplace=True
df_copy4.sort_values('Price', inplace=True)
print(f"✅ sort_values(inplace=True):")
print(f"Original modified: {list(df_copy4['Price'])}")

# 📝 4. FILLNA operations
print(f"\n📝 4. FILLNA OPERATIONS")
print("-" * 30)

# Create data with NaN
nan_df = pd.DataFrame({
    'A': [1, None, 3, None, 5],
    'B': [None, 2, None, 4, None]
})

print("Original with NaN:")
print(nan_df)

# fillna with inplace=False
filled = nan_df.fillna(0)
print(f"\n✅ fillna(inplace=False) - original unchanged:")
print("Original still has NaN:", nan_df.isna().sum().sum() > 0)
print("New has no NaN:", filled.isna().sum().sum() == 0)

# fillna with inplace=True
nan_df.fillna(0, inplace=True)
print(f"✅ fillna(inplace=True) - original modified:")
print("Original now has no NaN:", nan_df.isna().sum().sum() == 0)

🛠️ METHODS SUPPORTING INPLACE PARAMETER
==================================================
📊 Sample Dataset:
  Product  Price     Category  Stock
0  Laptop   1200  Electronics     10
1   Phone    800  Electronics      0
2  Tablet    600  Electronics     15
3   Phone    850  Electronics      8
4  Laptop   1100  Electronics     12

🗑️ 1. DROP OPERATIONS
------------------------------
✅ After drop(inplace=False) - returns new DataFrame:
Original shape: (5, 4), New shape: (5, 3)
✅ After drop(inplace=True) - modifies original:
Modified shape: (5, 3), Return value: None

🏷️ 2. RENAME OPERATIONS
------------------------------
✅ rename(inplace=False): Original columns unchanged
Original: ['Product', 'Price', 'Category', 'Stock']
New: ['Item_Name', 'Price', 'Category', 'Stock']
✅ rename(inplace=True): Original columns changed
Modified: ['Item_Name', 'Price', 'Category', 'Stock']

🔄 3. SORT OPERATIONS
------------------------------
✅ sort_values(inplace=False):
Original order preserved: [1200, 800, 600, 850, 1100]
New sorted order: [600, 800, 850, 1100, 1200]
✅ sort_values(inplace=True):
Original modified: [600, 800, 850, 1100, 1200]

📝 4. FILLNA OPERATIONS
------------------------------
Original with NaN:
     A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  NaN
3  NaN  4.0
4  5.0  NaN

✅ fillna(inplace=False) - original unchanged:
Original still has NaN: True
New has no NaN: True
✅ fillna(inplace=True) - original modified:
Original now has no NaN: True

**Complete Methods Reference**

| Method | Supports `inplace` | Default | Memory Impact | Use Case |
|--------|-------------------|---------|---------------|----------|
| **`drop()`** | ✅ Yes | `False` | High without inplace | Remove columns/rows |
| **`dropna()`** | ✅ Yes | `False` | High without inplace | Remove missing values |
| **`fillna()`** | ✅ Yes | `False` | High without inplace | Fill missing values |
| **`rename()`** | ✅ Yes | `False` | Medium without inplace | Rename columns/index |
| **`sort_values()`** | ✅ Yes | `False` | High without inplace | Sort by values |
| **`sort_index()`** | ✅ Yes | `False` | High without inplace | Sort by index |
| **`reset_index()`** | ✅ Yes | `False` | Medium without inplace | Reset index |
| **`set_index()`** | ✅ Yes | `False` | Medium without inplace | Set new index |
| **`replace()`** | ✅ Yes | `False` | High without inplace | Replace values |
| **`assign()`** | ❌ No | N/A | Always creates copy | Add new columns |
| **`merge()`** | ❌ No | N/A | Always creates copy | Join DataFrames |
| **`concat()`** | ❌ No | N/A | Always creates copy | Concatenate DataFrames |

## Independent Practice:

### Practice exercise 1

#### 

Read the file *Top 10 Albums By Year.csv*. This file contains the top 10 albums for each year from 1990 to 2021. Each row corresponds to a unique album.

#### 

Print the summary statistics of the data, and answer the following questions:

1. What proportion of albums have 15 or lesser tracks? Mention a range for the proportion.
2. What is the mean length of a track (in minutes)?

####

Why is `Worldwide Sales` not included in the summary statistics table printed in the above step?

####

Update the DataFrame so that `Worldwide Sales` is included in the summary statistics table. Print the summary statistics table.

**Hint**: Sometimes it may not be possible to convert an object to numeric(). For example, the object ‘hi’ cannot be converted to a numeric() by the python compiler. To avoid getting an error, use the `errors` argument of `to_numeric()` to force such conversions to NaN (missing value).

####

Create a new column called `mean_sales_per_year` that computes the average worldwide sales per year for each album, assuming that the worldwide sales are as of 2022. Print the first 5 rows of the updated DataFrame.

####

Find the album having the highest worldwide sales per year, and its artist.

#### 
Subset the data to include only Hip-Hop albums. How many Hip_Hop albums are there?

####

Which album amongst hip-hop has the higest mean sales per year per track, and who is its artist?

### Practice exercise 2

#### 
Read the file *STAT303-1 survey for data analysis.csv*.

#### 
How many observations and variables are there in the data?

#### 
Rename all the columns of the data, except the first two columns, with the shorter names in the list `new_col_names` given below. The order of column names in the list is the same as the order in which the columns are to be renamed starting with the third column from the left.

#### 
Rename the following columns again:

1. Rename `do_you_smoke` to `smoke`.

2. Rename `are_you_an_introvert_or_extrovert` to `introvert_extrovert`.

**Hint:** Use the function [rename()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html)

#### 
Find the proportion of people going to more than 4 parties per month. Use the variable `parties_per_month`.

#### 
Among the people who go to more than 4 parties a month, what proportion of them are introverts?

#### 
Find the proportion of people in each category of the variable `how_happy`.

#### 
Among the people who go to more than 4 parties a month, what proportion of them are either `Pretty happy` or `Very happy`?

#### 
Examine the column `num_insta_followers`. Some numbers in the column contain a comma(`,`) or a tilde(`~`). Remove both these characters from the numbers in the column. 

**Hint:** You may use the function [str.replace()](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html) of the Pandas Series class.

#### 
Convert the column `num_insta_followers` to numeric. Coerce the errors.

#### 
What is the mean `internet_hours_per_day` for the top 46 people in terms of number of instagram followers?

#### 
What is the mean `internet_hours_per_day` for the remaining people?

### Practice exercise 3

#### 
Use the updated dataset from Practice exercise 2.

The last four variables in the dataset are: 

1. `cant_change_math_ability`

2. `can_change_math_ability`

3. `math_is_genetic`

4. `much_effort_is_lack_of_talent`

Each of the above variables has values - `Agree` / `Disagree`. Replace `Agree` with `1` and `Disagree` with `0`.

**Hint :** You can do it with any one of the following methods:

1. Use the map() function

2. Use the apply() function with the lambda function

3. Use the replace() function


Two of the above methods avoid a `for`-loop. Which ones?